import { describe, expect, it } from 'vitest';
import { FMT, P, ROOT, SETTINGS, rig } from './helpers.js';

const add = (o: object = {}) => ({ kind: 'add' as const, engine: 'claude-code' as const, scope: 'project' as const, event: 'PostToolUse', def: FMT, root: ROOT, ...o });
describe('acceptance 4: hash-bound confirmation and scope', () => {
  it('a stale plan hash writes nothing', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add()); await expect(r.mgr.apply(plan, { accepted: true, planHash: 'x'.repeat(64) })).rejects.toMatchObject({ code: 'plan_changed', name: 'PlanChanged' }); expect(r.counts.writes).toBe(0); expect(r.files.get(P.project)).toBe(SETTINGS); });
  it('a plan whose text was edited after planning is refused', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add()); await expect(r.mgr.apply({ ...plan, newText: '{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"evil"}]}]}}' }, { accepted: true, planHash: plan.planHash })).rejects.toMatchObject({ code: 'plan_changed' }); expect(r.counts.writes).toBe(0); });
  it('the file changing after the plan is refused', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add()); r.files.set(P.project, SETTINGS + ' '); await expect(r.mgr.apply(plan, { accepted: true, planHash: plan.planHash })).rejects.toMatchObject({ code: 'plan_changed' }); expect(r.counts.writes).toBe(0); });
  it('without accepted: true nothing is written', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add()); for (const c of [undefined, {}, { accepted: false, planHash: plan.planHash }, { planHash: plan.planHash }]) await expect(r.mgr.apply(plan, c as never)).rejects.toMatchObject({ code: 'not_confirmed' }); expect(r.counts.writes).toBe(0); });
  it('user scope needs userScope: true', async () => { const r = rig({ [P.user]: '{}' }); const plan = await r.mgr.plan(add({ scope: 'user' })); await expect(r.mgr.apply(plan, { accepted: true, planHash: plan.planHash })).rejects.toMatchObject({ code: 'needs_user_confirm' }); expect(r.counts.writes).toBe(0); await r.mgr.apply(plan, { accepted: true, planHash: plan.planHash, userScope: true }); expect(r.counts.writes).toBe(2); });
  it('local scope writes settings.local.json and project scope never touches it', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add({ scope: 'local' })); expect(plan.path).toBe(P.local); await r.mgr.apply(plan, { accepted: true, planHash: plan.planHash }); expect(r.files.get(P.project)).toBe(SETTINGS); });
});
describe('acceptance 8: unusable files and backups', () => {
  it('invalid JSON, a non-object, a bad hooks value and a file over 1 MiB are refused and untouched', async () => { for (const text of ['{ "a": ', '[]', '{"hooks": 5}', '{"x":"' + 'a'.repeat(1024 * 1024) + '"}']) { const r = rig({ [P.project]: text }); await expect(r.mgr.plan(add())).rejects.toMatchObject({ code: 'settings_invalid', name: 'SettingsInvalid' }); expect(r.files.get(P.project)).toBe(text); expect(r.counts.writes).toBe(0); } });
  it('the message says where, without quoting the file', async () => { const r = rig({ [P.project]: '{\n "token": "ghp_' + 'A'.repeat(36) + '"\n "x": 1}' }); const e = await r.mgr.plan(add()).catch((x) => x); expect(e.message).toContain('line 3'); expect(e.message).not.toContain('ghp_'); });
  it('keeps exactly the 5 newest backups after 7 edits', async () => {
    const r = rig({ [P.project]: SETTINGS }); const names: string[] = [];
    for (let i = 0; i < 7; i++) { const plan = await r.mgr.plan(add({ def: { command: `echo ${i}` }, event: 'Stop' })); const rep = await r.mgr.apply(plan, { accepted: true, planHash: plan.planHash }); names.push(rep.backup!); await r.clock.advance(1000); }
    const left = [...r.files.keys()].filter((k) => k.includes('.centcom-bak.')).sort(); expect(left).toEqual(names.slice(2).sort()); expect(JSON.parse(r.files.get(left[0]!)!).hooks.Stop).toHaveLength(2); // the oldest kept is the file as it was before the 3rd edit
  });
  it('two edits in the same second still get separate backups', async () => { const r = rig({ [P.project]: SETTINGS }); const reps = []; for (let i = 0; i < 2; i++) { const plan = await r.mgr.plan(add({ def: { command: `echo ${i}` }, event: 'Stop' })); reps.push(await r.mgr.apply(plan, { accepted: true, planHash: plan.planHash })); } expect(new Set(reps.map((x) => x.backup)).size).toBe(2); });
  it('an unwritable file: typed error, nothing changed, no backup left', async () => { const r = rig({ [P.project]: SETTINGS }); const plan = await r.mgr.plan(add()); r.failWrites((p) => p === P.project); await expect(r.mgr.apply(plan, { accepted: true, planHash: plan.planHash })).rejects.toMatchObject({ code: 'unwritable' }); expect(r.files.get(P.project)).toBe(SETTINGS); expect([...r.files.keys()].filter((k) => k.includes('centcom-bak'))).toEqual([]); const r2 = rig({ [P.project]: SETTINGS }); const p2 = await r2.mgr.plan(add()); r2.failWrites((p) => p.includes('centcom-bak')); await expect(r2.mgr.apply(p2, { accepted: true, planHash: p2.planHash })).rejects.toMatchObject({ code: 'unwritable' }); expect(r2.files.get(P.project)).toBe(SETTINGS); });
});
describe('acceptance 5 and 6', () => {
  it('sessionSettingsArg is JSON with only the given hooks and writes no file', () => { const r = rig(); const s = r.mgr.sessionSettingsArg([{ event: 'PostToolUse', ...FMT }, { event: 'Stop', command: 'echo done' }]); expect(JSON.parse(s)).toEqual({ hooks: { PostToolUse: [{ matcher: 'Edit|Write', hooks: [{ type: 'command', command: FMT.command, timeout: 60 }] }], Stop: [{ hooks: [{ type: 'command', command: 'echo done' }] }] } }); expect(Object.keys(JSON.parse(s))).toEqual(['hooks']); expect(r.counts.writes).toBe(0); expect(() => r.mgr.sessionSettingsArg([{ event: 'Nope', command: 'x' }])).toThrow(); expect(() => r.mgr.sessionSettingsArg([{ event: 'Stop', command: 'x', timeout_s: 0 }])).toThrow(); });
  it('codex: list says unsupported and plan throws CapabilityMissing', async () => { const r = rig({ [P.project]: SETTINGS }); expect((await r.mgr.list(ROOT)).codex).toMatchObject({ supported: false }); await expect(r.mgr.plan(add({ engine: 'codex' }))).rejects.toMatchObject({ name: 'CapabilityMissing', code: 'capability_missing' }); expect(r.counts.writes).toBe(0); });
});
describe('review flags for shared files', () => {
  const text = '{"hooks":{"Stop":[{"hooks":[{"type":"command","command":"echo a"}]}]}}';
  it('flags a project file nobody here confirmed, then a change after a git pull, not the personal file', async () => {
    const r = rig({ [P.project]: text, [P.local]: text }, { confirmed: true }); const flags = async () => { const l = await r.mgr.list(ROOT); if (!l.claude.supported) throw new Error('x'); return l.claude.entries.map((e) => [e.scope, e.review]); };
    expect(await flags()).toEqual([['project', 'never_confirmed'], ['local', undefined]]); await r.mgr.markReviewed(P.project); expect(await flags()).toEqual([['project', undefined], ['local', undefined]]);
    r.files.set(P.project, text.replace('echo a', 'echo b')); expect(await flags()).toEqual([['project', 'changed_since_confirmed'], ['local', undefined]]);
    const plan = await r.mgr.plan(add({ event: 'Notification', def: { command: 'echo n' } })); await r.mgr.apply(plan, { accepted: true, planHash: plan.planHash }); expect((await flags())[0]).toEqual(['project', undefined]);
  });
  it('a change to other keys does not count as a hooks change', async () => { const r = rig({ [P.project]: text }, { confirmed: true }); await r.mgr.markReviewed(P.project); r.files.set(P.project, '{"env":{"A":"1"},"hooks":{"Stop":[{"hooks":[{"type":"command","command":"echo a"}]}]}}'); const l = await r.mgr.list(ROOT); if (!l.claude.supported) throw new Error('x'); expect(l.claude.entries[0]!.review).toBeUndefined(); });
});
