import { describe, expect, it } from 'vitest';
import { FMT, P, ROOT, SETTINGS, rig } from './helpers.js';

const codes = (r: ReturnType<typeof rig>, def: object, event?: string) => r.mgr.validate(def as never, event).map((i) => i.code);
describe('validation (every issue code)', () => {
  it('bad_timeout for 0, 601, 1.5 and text; fine for 1 and 600', () => { const r = rig(); for (const t of [0, 601, 1.5, '5']) expect(codes(r, { command: 'x', timeout_s: t })).toEqual(['bad_timeout']); for (const t of [1, 600]) expect(codes(r, { command: 'x', timeout_s: t })).toEqual([]); });
  it('too_long above 1,024 characters and for an empty command', () => { const r = rig(); expect(codes(r, { command: 'x'.repeat(1025) })).toEqual(['too_long']); expect(codes(r, { command: 'x'.repeat(1024) })).toEqual([]); expect(codes(r, { command: '  ' })).toEqual(['too_long']); });
  it('bad_matcher for a broken regular expression, a non-string and a long one', () => { const r = rig(); expect(codes(r, { command: 'x', matcher: '(' })).toEqual(['bad_matcher']); expect(codes(r, { command: 'x', matcher: 5 })).toEqual(['bad_matcher']); expect(codes(r, { command: 'x', matcher: 'a'.repeat(257) })).toEqual(['bad_matcher']); for (const m of ['Edit|Write', '*', '']) expect(codes(r, { command: 'x', matcher: m })).toEqual([]); });
  it('unknown_event', () => { const r = rig(); expect(codes(r, { command: 'x' }, 'Frobnicate')).toEqual(['unknown_event']); expect(codes(r, { command: 'x' }, 'Stop')).toEqual([]); });
  it('command_not_found looks at PATH only, and only for the first word', () => { const seen: string[] = []; const r = rig({}, { which: (c) => { seen.push(c); return c === 'jq' ? '/usr/bin/jq' : undefined; } }); expect(codes(r, { command: "jq -r . | nosuch" }, 'Stop')).toEqual([]); expect(codes(r, { command: 'FOO=1 nosuchtool --x' }, 'Stop')).toEqual(['command_not_found']); expect(seen).toEqual(['jq', 'nosuchtool']); });
  it('shell keywords and built-ins are not looked up on PATH', () => { const r = rig({}, { which: () => undefined }); for (const c of ['if true; then echo x; fi', 'echo hi', 'cd /x']) expect(codes(r, { command: c }, 'Stop'), c).toEqual([]); expect(codes(r, { command: 'nosuch --x' }, 'Stop')).toEqual(['command_not_found']); });
  it('too_many when a ninth hook is added (acceptance 2): plan refuses', async () => {
    const eight = JSON.stringify({ hooks: { Stop: Array.from({ length: 8 }, (_, i) => ({ hooks: [{ type: 'command', command: `echo ${i}` }] })) } }); const r = rig({ [P.project]: eight });
    await expect(r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: 'echo 9' }, root: ROOT })).rejects.toMatchObject({ code: 'too_many' }); expect(r.counts.writes).toBe(0);
    const nine = rig({ [P.project]: JSON.stringify({ hooks: { Stop: [{ hooks: Array.from({ length: 8 }, (_, i) => ({ type: 'command', command: `e${i}` })) }] } }) }); await expect(nine.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: 'z' }, root: ROOT })).rejects.toMatchObject({ code: 'too_many' });
  });
  it('plan refuses bad timeouts and adding to an unknown event', async () => { const r = rig({ [P.project]: SETTINGS }); const add = (o: object) => r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'PostToolUse', root: ROOT, ...o }); await expect(add({ def: { ...FMT, timeout_s: 0 } })).rejects.toMatchObject({ code: 'invalid_hook', detail: 'bad_timeout' }); await expect(add({ def: { ...FMT, timeout_s: 601 } })).rejects.toMatchObject({ detail: 'bad_timeout' }); await expect(add({ event: 'Frobnicate', def: FMT })).rejects.toMatchObject({ code: 'invalid_hook' }); });
  it('a command that is not on PATH is a warning, not a refusal', async () => { const r = rig({ [P.project]: SETTINGS }, { which: () => undefined }); const plan = await r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: 'nosuch' }, root: ROOT }); expect(plan.issues.map((i) => i.code)).toEqual(['command_not_found']); });
  it('refuses a command with a secret, without echoing it', async () => { const r = rig({ [P.project]: SETTINGS }); const secret = 'sk-ant-api03-' + 'a'.repeat(40); const err = await r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: `curl -H "x-api-key: ${secret}" x` }, root: ROOT }).catch((e) => e); expect(err.code).toBe('secret_rejected'); expect(JSON.stringify([err.message, err.detail])).not.toContain(secret); const gh = await r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: 'echo ghp_' + 'A'.repeat(36) }, root: ROOT }).catch((e) => e); expect(gh.code).toBe('secret_rejected'); });
});
describe('acceptance 3: unknown events survive', () => {
  const text = '{"hooks":{"Frobnicate":[{"hooks":[{"type":"command","command":"keep me"}]}],"Stop":[{"hooks":[{"type":"command","command":"a"}]}]}}';
  it('is listed with unknown_event and never deleted', async () => { const r = rig({ [P.project]: text }); const l = await r.mgr.list(ROOT); if (!l.claude.supported) throw new Error('x'); expect(l.claude.entries.find((e) => e.event === 'Frobnicate')!.issues.map((i) => i.code)).toEqual(['unknown_event']);
    const plan = await r.mgr.plan({ kind: 'add', engine: 'claude-code', scope: 'project', event: 'Stop', def: { command: 'b' }, root: ROOT }); expect(JSON.parse(plan.newText).hooks.Frobnicate).toEqual(JSON.parse(text).hooks.Frobnicate); expect(plan.newText).toContain('"Frobnicate":[{"hooks":[{"type":"command","command":"keep me"}]}]');
    const rm = await r.mgr.plan({ kind: 'remove', engine: 'claude-code', scope: 'project', event: 'Stop', index: 0, root: ROOT }); expect(JSON.parse(rm.newText).hooks.Frobnicate).toBeDefined(); });
});
