import { describe, expect, it } from 'vitest';
import { AWAY_AFTER, NudgeLimiter, PresencePublisher, TYPING_CLEAR, TYPING_DEBOUNCE, type Sink } from '../../shell/src/presence/publisher.js';

const clock = () => { let t = 0; const q: { at: number; fn: () => void; h: number }[] = []; let id = 0; return { now: () => t, setTimeout: (fn: () => void, ms: number) => { const h = ++id; q.push({ at: t + ms, fn, h }); return h; }, clearTimeout: (h: unknown) => { const i = q.findIndex((x) => x.h === h); if (i >= 0) q.splice(i, 1); }, advance(ms: number) { const end = t + ms; for (;;) { q.sort((a, b) => a.at - b.at); const n = q[0]; if (!n || n.at > end) break; q.shift(); t = n.at; n.fn(); } t = end; } }; };
const make = () => { const c = clock(); const updates: { at: number; b: unknown }[] = []; const cursors: { at: number; c: unknown }[] = []; const sink: Sink = { update: (b) => void updates.push({ at: c.now(), b }), cursor: (x) => void cursors.push({ at: c.now(), c: x }) }; return { c, updates, cursors, p: new PresencePublisher(sink, c) }; };
describe('publisher (acceptance 3)', () => {
  it('under 100 events a second: at most one update a second and ten cursors a second', () => { const m = make(); for (let i = 0; i < 300; i++) { m.c.advance(10); m.p.input(true); m.p.setAgents(i % 3, i % 2 === 0); m.p.cursor({ line: i }); } m.c.advance(2000); const gaps = m.updates.slice(1).map((u, i) => u.at - m.updates[i]!.at); expect(gaps.every((g) => g >= 1000)).toBe(true); const perSecond = (xs: { at: number }[]): number => Math.max(...xs.map((x) => xs.filter((y) => y.at >= x.at && y.at < x.at + 1000).length)); expect(perSecond(m.updates)).toBeLessThanOrEqual(1); expect(perSecond(m.cursors)).toBeLessThanOrEqual(10); expect((m.cursors.at(-1)!.c as { line: number }).line).toBe(299); });
  it('nothing is sent for what has not changed', () => { const m = make(); m.p.setStatus('online'); m.c.advance(5000); expect(m.updates).toHaveLength(1); /* the first state is announced once */ m.p.setStatus('online'); m.c.advance(5000); expect(m.updates).toHaveLength(1); m.p.setStatus('busy'); m.c.advance(1); expect(m.updates).toHaveLength(2); m.p.setStatus('busy'); m.c.advance(5000); expect(m.updates).toHaveLength(2); m.p.cursor({ line: 1 }); m.p.cursor({ line: 1 }); m.c.advance(1000); expect(m.cursors).toHaveLength(1); });
  it('typing shows after 400 ms of keys and clears 5 s after the last keystroke', () => { const m = make(); m.p.input(true); m.c.advance(TYPING_DEBOUNCE - 1); expect(m.updates).toHaveLength(0); m.c.advance(1); expect(m.updates[0]!.b).toMatchObject({ activity: 'typing' }); m.c.advance(2000); m.p.input(true); m.c.advance(TYPING_CLEAR - 1); expect(m.updates).toHaveLength(1); m.c.advance(1); m.c.advance(1000); expect(m.updates.at(-1)!.b).toMatchObject({ activity: 'idle' }); });
  it('away after 5 minutes without input, back on the next input, busy is the person\'s own choice and beats away', () => { const m = make(); m.c.advance(AWAY_AFTER); expect(m.updates.at(-1)!.b).toMatchObject({ status: 'away' }); m.p.input(); m.c.advance(1000); expect(m.updates.at(-1)!.b).toMatchObject({ status: 'online' }); m.p.setStatus('busy'); m.c.advance(1000); m.c.advance(AWAY_AFTER); expect(m.updates.at(-1)!.b).toMatchObject({ status: 'busy' }); });
  it('a refusing sink and a disposed publisher are harmless', () => { const c = clock(); const p = new PresencePublisher({ update: () => { throw new Error('no'); }, cursor: () => { throw new Error('no'); } }, c); p.setStatus('busy'); p.cursor({ line: 1 }); c.advance(2000); p.dispose(); p.setStatus('online'); p.cursor({ line: 2 }); c.advance(5000); expect(p.sent.update).toBe(1); });
  it('one nudge per person a minute', () => { let t = 0; const n = new NudgeLimiter(() => t); expect(n.allow('a')).toBe(true); expect(n.allow('a')).toBe(false); expect(n.allow('b')).toBe(true); t = 59_999; expect(n.allow('a')).toBe(false); t = 60_000; expect(n.allow('a')).toBe(true); });
});
