import { describe, expect, it } from 'vitest';
import { RosterStore } from '../../src/presence/roster.js';
import { visibleCursors } from '../../src/presence/cursors.js';

const members = [{ id: 'me', name: 'Me', slot: 0 }, { id: 'ada', name: 'Ada', slot: 1 }, { id: 'ben', name: 'Ben', slot: 3 }];
const cur = (member: string, at = 0, o: Record<string, unknown> = {}) => ({ member, path: 'a.ts', line: 3, col: 1, receivedAt: at, ...o });
describe('cursors (acceptance 4)', () => {
  const at = (ms: number) => visibleCursors([cur('ada')], { me: 'me', path: 'a.ts', members, now: ms })[0];
  it('full for 3 s, 40 % until 10 s, then gone', () => { expect(at(2999)!.opacity).toBe(1); expect(at(3000)!.opacity).toBe(0.4); expect(at(9999)!.opacity).toBe(0.4); expect(at(10_000)).toBeUndefined(); });
  it('your own cursor, strangers, other files and cursors without a line are not drawn; colours come from the slot', () => { const m = visibleCursors([cur('me'), cur('ghost'), cur('ada', 0, { path: 'b.ts' }), cur('ben', 0, { line: undefined }), cur('ada'), cur('ben')], { me: 'me', path: 'a.ts', members, now: 100 }); expect(m.map((x) => [x.member, x.colour, x.initial])).toEqual([['ada', 'red', 'A'], ['ben', 'green', 'B']]); });
  it('the clock on the frame does not matter: only the time it was received here', () => { expect(visibleCursors([cur('ada', 5000, { ts: '1999-01-01' })], { me: 'me', path: 'a.ts', members, now: 5100 })).toHaveLength(1); });
  it('when the member leaves the roster the cursor goes at once, whatever its age', () => { const r = new RosterStore(); r.apply({ kind: 'control.roster', from: 'srv', p: { version: 1, members: [{ id: 'me', name: 'Me', slot: 0, role: 'host' }, { id: 'ada', name: 'Ada', slot: 1, role: 'editor' }] } }); const list = () => r.list().map((m) => ({ id: m.id, name: m.name, slot: m.slot })); expect(visibleCursors([cur('ada', 100)], { me: 'me', path: 'a.ts', members: list(), now: 101 })).toHaveLength(1); r.apply({ kind: 'control.member_left', from: 'srv', p: { member: 'ada', code: 'leave' } }); expect(visibleCursors([cur('ada', 100)], { me: 'me', path: 'a.ts', members: list(), now: 101 })).toHaveLength(0); });
});
describe('roster from control frames', () => {
  const roster = (v: number, ids: string[]) => ({ kind: 'control.roster', from: 'srv', p: { version: v, members: ids.map((id, i) => ({ id, name: id.toUpperCase(), slot: i, role: i === 0 ? 'host' : 'editor' })) } });
  it('server-only frames from a member are ignored; an older full roster does not replace a newer one', () => { const r = new RosterStore(); r.apply(roster(3, ['a', 'b'])); r.apply({ kind: 'control.roster', from: 'mal', p: { version: 9, members: [] } }); expect(r.list()).toHaveLength(2); r.apply(roster(2, ['z'])); expect(r.list().map((m) => m.id)).toEqual(['a', 'b']); r.apply(roster(4, ['a', 'b', 'c'])); expect(r.list()).toHaveLength(3); r.apply({ kind: 'control.member_joined', from: 'b', p: { member: 'x' } }); expect(r.get('x')).toBeUndefined(); });
  it('join and leave events fire once; role changes come only from the host; host change is atomic', () => { const r = new RosterStore(); const ev: string[] = []; r.onChange((e) => ev.push(`${e.type}:${e.member.name}`)); r.apply(roster(1, ['a', 'b'])); r.apply({ kind: 'control.member_joined', from: 'srv', p: { member: 'c', name: 'Maya', slot: 2, role: 'editor' } }); r.apply({ kind: 'control.member_joined', from: 'srv', p: { member: 'c', name: 'Maya', slot: 2, role: 'editor' } }); r.apply({ kind: 'control.member_left', from: 'srv', p: { member: 'c', code: 'leave' } }); r.apply({ kind: 'control.member_left', from: 'srv', p: { member: 'c', code: 'leave' } }); expect(ev).toEqual(['joined:Maya', 'left:Maya']);
    r.apply({ kind: 'control.role', from: 'b', p: { member: 'b', role: 'host' } }); expect(r.get('b')!.role).toBe('editor'); r.apply({ kind: 'control.role', from: 'a', p: { member: 'b', role: 'viewer' } }); expect(r.get('b')!.role).toBe('viewer'); r.apply({ kind: 'control.host_changed', from: 'srv', p: { host: 'b', code: 'transfer' } }); expect(r.host()!.id).toBe('b'); expect(r.get('a')!.role).toBe('editor'); });
  it('a sender not in the roster is held for 10 s and then dropped', () => { let t = 0; const r = new RosterStore(() => t); expect(r.known('x')).toBe(false); expect(r.heldCount()).toBe(1); t = 9999; expect(r.heldCount()).toBe(1); t = 10_001; expect(r.heldCount()).toBe(0); r.apply(roster(1, ['x'])); expect(r.known('x')).toBe(true); });
});
