// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import React from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { setMotion } from '../../shell/src/a11y/index.js';
import { ConflictList, FleetBoard } from '../../shell/src/fleet/components.js';
import { elapsed, middleTruncate, motionPlan } from '../../shell/src/fleet/model.js';
import { ev, spawn, state, store } from './helpers.js';

afterEach(() => { cleanup(); setMotion(undefined); });
describe('16 agents (acceptance 1, 7)', () => {
  it('render in under 100 ms and at most 6 mascots may move', () => { const s = store(16); const cards = s.cards(); const run = (): { ms: number; container: HTMLElement } => { const t = performance.now(); const r = render(<FleetBoard cards={cards} now={Date.UTC(2026, 9, 7, 12, 1)} view="cards" />); return { ms: performance.now() - t, container: r.container }; }; run(); cleanup(); const times: number[] = []; let container!: HTMLElement; for (let i = 0; i < 5; i++) { const r = run(); times.push(r.ms); container = r.container; if (i < 4) cleanup(); } /* the best of five: a busy machine slows a run, not all of them */ expect(Math.min(...times)).toBeLessThan(100); expect(container.querySelectorAll('article')).toHaveLength(16); expect(container.querySelectorAll('[data-mascot-slot][data-paused="false"]').length).toBeLessThanOrEqual(6); expect(container.querySelectorAll('[data-mascot-slot][data-paused="true"]').length).toBeGreaterThanOrEqual(10); });
  it('exactly one running card glows; under reduced motion nothing animates and the glow class stays (the stylesheet makes it a still border)', () => {
    const cards = store(16).cards(); const full = motionPlan(cards, false); expect(full.animated.size).toBe(6); expect(full.glow).toBeTruthy(); expect(motionPlan(cards, true).animated.size).toBe(0); const { container } = render(<FleetBoard cards={cards} now={0} view="cards" />); expect(container.querySelectorAll('.cc-agent--glow')).toHaveLength(1); act(() => setMotion('reduced')); expect(container.querySelectorAll('[data-mascot-slot][data-paused="false"]')).toHaveLength(0); expect(container.querySelectorAll('.cc-agent--glow')).toHaveLength(1);
  });
  it('a board with no agents says so; the compact table has the same rows', () => { const { rerender, container } = render(<FleetBoard cards={[]} now={0} view="cards" />); expect(screen.getByText('No agents yet')).toBeTruthy(); const cards = store(4).cards(); rerender(<FleetBoard cards={cards} now={0} view="table" />); expect(container.querySelectorAll('tbody tr')).toHaveLength(4); expect(screen.getByRole('region', { name: 'Agents' })).toBeTruthy(); });
});
describe('cards and keys (acceptance 4, 6)', () => {
  it('every card has a glyph and a word, not just a colour, and an accessible name with its owner', () => { const s = store(); spawn(s, 'a', 'mem_b'); state(s, 'a', 'awaiting-approval', 'mem_b'); spawn(s, 'b'); state(s, 'b', 'error'); spawn(s, 'c'); state(s, 'c', 'editing-file'); render(<FleetBoard cards={s.cards()} now={Date.now()} view="cards" />); const names = screen.getAllByRole('article').map((a) => a.getAttribute('aria-label')); expect(names[0]).toBe('Agent 2, Something went wrong, Ada'); expect(names[1]).toBe('Agent 1, Cento is waiting for an approval, Ben'); const text = document.body.textContent!; for (const g of ['?', '!', '▶']) expect(text).toContain(g); });
  it('j and k move between cards, Enter opens the details, one tab stop, buttons at least 32 px by their class', () => {
    const open = vi.fn(); const cards = store(4).cards(); render(<FleetBoard cards={cards} now={0} view="cards" onOpen={open} />); const arts = screen.getAllByRole('article'); expect(arts.map((a) => a.tabIndex)).toEqual([0, -1, -1, -1]); arts[0]!.focus(); fireEvent.keyDown(arts[0]!, { key: 'j' }); expect(document.activeElement).toBe(arts[1]); expect(arts[1]!.tabIndex).toBe(0); fireEvent.keyDown(arts[1]!, { key: 'k' }); expect(document.activeElement).toBe(arts[0]); fireEvent.keyDown(arts[0]!, { key: 'k' }); expect(document.activeElement).toBe(arts[0]); fireEvent.keyDown(arts[1]!, { key: 'Enter' }); expect(open).toHaveBeenCalledWith(cards[1]!.agentId); fireEvent.keyDown(screen.getAllByText('Details')[0]!, { key: 'j' }); expect(document.activeElement).toBe(arts[0]);
  });
  it('merge buttons appear only on your own agent with something to merge, and they only call back', () => { const s = store(); spawn(s, 'a'); state(s, 'a', 'editing-file'); s.apply(ev('branch.update', 'mem_me', {}, { agent_id: 'a', branch: 'x', head: 'h', ahead: 3, behind: 1, dirty: false })); spawn(s, 'b', 'mem_b'); state(s, 'b', 'editing-file', 'mem_b'); s.apply(ev('branch.update', 'mem_b', {}, { agent_id: 'b', branch: 'y', head: 'h', ahead: 2, behind: 0, dirty: false })); const merge = vi.fn(); render(<FleetBoard cards={s.cards()} now={0} view="cards" onMerge={merge} />); expect(screen.getAllByText('Merge')).toHaveLength(1); fireEvent.click(screen.getByText('Merge')); expect(merge).toHaveBeenCalledWith('a', 'merge'); expect(document.body.textContent).toContain('3 ahead, 1 behind'); });
  it('locks and conflicts are listed in words with the `!` glyph', () => { const s = store(); spawn(s, 'a'); spawn(s, 'b', 'mem_b'); s.apply(ev('file.lock', 'mem_me', { action: 'acquire', path_hmac: 'h'.repeat(43), agent_id: 'a', ttl_ms: 30000 })); s.apply(ev('conflict.detected', 'mem_b', { agent_ids: ['a', 'b'], path_hmacs: ['h'.repeat(43)] })); render(<ConflictList cards={s.cards()} />); expect(screen.getByText('! Merge conflict')).toBeTruthy(); expect(document.body.textContent).toMatch(/Agent [12] and Agent [12] changed the same file/); expect(document.body.textContent).toMatch(/Agent [12] holds a file/); });
  it('helpers: middle truncation keeps both ends, time reads as elapsed', () => { expect(middleTruncate('agent/refactor-the-whole-session-engine', 20)).toMatch(/^agent\/refa….*engine$/); expect(middleTruncate('short')).toBe('short'); expect(elapsed('2026-10-07T12:00:00Z', Date.UTC(2026, 9, 7, 12, 0, 45))).toBe('45s'); expect(elapsed('2026-10-07T12:00:00Z', Date.UTC(2026, 9, 7, 12, 3, 5))).toBe('3m 05s'); expect(elapsed('2026-10-07T12:00:00Z', Date.UTC(2026, 9, 7, 14, 5))).toBe('2h 05m'); expect(elapsed(undefined, 0)).toBe(''); });
});
