/** Writes the CLI reference pages and the man pages from the command list in apps/cli/src/help. `--check` fails when the files on disk are not what it would write. */
import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONTRACT_VERSION } from '../../packages/protocol/src/index.js';
import { COMMANDS, type CommandMeta } from '../../apps/cli/src/help/commands.js';
import { ENV_VARS, EXIT_CODES, RELAY_NEVER, RELAY_VISIBLE, TRAFFIC_NOTE } from '../../apps/cli/src/help/topics.js';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
/** The version the CLI prints for --version (the VERSION constant of main.tsx). */
export const version = (): string => /const VERSION = '([^']+)'/.exec(readFileSync(join(ROOT, 'apps/cli/src/main.tsx'), 'utf8'))?.[1] ?? '0.0.0';
const walkSrc = (d: string): string[] => (existsSync(d) ? readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.name === 'node_modules' || e.name === 'test' || e.name === 'help' ? [] : e.isDirectory() ? walkSrc(join(d, e.name)) : /\.(ts|tsx)$/.test(e.name) ? [join(d, e.name)] : [])) : []);
/** All product source text (no tests, no help tables): what decides whether a documented variable really exists. */
export const sourcesText = (): string => ['apps', 'packages'].flatMap((d) => walkSrc(join(ROOT, d))).map((f) => readFileSync(f, 'utf8')).join('\n');
const flagText = (f: CommandMeta['flags'][number]) => `${f.flag}${f.arg ? ' ' + f.arg : ''}`;

export function referencePage(c: CommandMeta): string {
  return ['<!-- Generated by tools/docs/gen-cli-reference.ts from apps/cli/src/help/commands.ts. Do not edit. -->', `# ${c.name}`, '', c.description, '', '```', c.usage, '```', '',
    ...(c.flags.length ? ['## Options', '', ...c.flags.map((f) => `- \`${flagText(f)}\`: ${f.description}`), ''] : []), ...(c.examples?.length ? ['## Examples', '', '```sh', ...c.examples, '```', ''] : [])].join('\n');
}
const roff = (s: string) => s.replace(/\\/g, '\\\\').replace(/^\./gm, '\\&.').replace(/-/g, '\\-');
export function manPage(c: CommandMeta, v: string, contract: string): string {
  const title = c.name === 'centcom' ? 'CENTCOM' : `CENTCOM-${c.name.toUpperCase()}`; const name = c.name === 'centcom' ? 'centcom' : `centcom-${c.name}`;
  return ['.\\" Generated by tools/docs/gen-cli-reference.ts from apps/cli/src/help/commands.ts. Do not edit.', `.TH ${title} 1 "" "centcom ${v} (contract ${contract})" "Centcom"`, '.SH NAME', `${roff(name)} \\- ${roff(c.summary)}`, '.SH SYNOPSIS', `.B ${roff(c.usage)}`, '.SH DESCRIPTION', roff(c.description),
    ...(c.flags.length ? ['.SH OPTIONS', ...c.flags.flatMap((f) => ['.TP', `.B ${roff(flagText(f))}`, roff(f.description)])] : []), ...(c.examples?.length ? ['.SH EXAMPLES', ...c.examples.flatMap((e) => ['.PP', '.nf', roff(e), '.fi'])] : []),
    '.SH SEE ALSO', 'centcom help, https://centcom.dev/docs', ''].join('\n');
}
/** Only variables the code really reads are documented, so a page never promises something that is not there yet. */
export const liveEnv = () => { const src = sourcesText(); return ENV_VARS.filter((v) => src.includes(v.name)); };
export function envPage(): string { return ['<!-- Generated. Do not edit. -->', '# Environment variables', '', '| Variable | What it does |', '|---|---|', ...liveEnv().map((v) => `| \`${v.name}\` | ${v.description} |`), ''].join('\n'); }
export function exitPage(): string { return ['<!-- Generated. Do not edit. -->', '# Exit codes of `centcom -p`', '', '| Code | Meaning |', '|---|---|', ...EXIT_CODES.map(([c, t]) => `| ${c} | ${t} |`), ''].join('\n'); }
export function privacyList(): string { return ['<!-- Generated. Do not edit. -->', '## What the relay can see', '', ...RELAY_VISIBLE.map((x) => `- ${x}`), '', '## What it never sees', '', ...RELAY_NEVER.map((x) => `- ${x}`), '', TRAFFIC_NOTE, ''].join('\n'); }

/** Every generated file, by path under the repo. */
export function generated(): Record<string, string> {
  const v = version(); const out: Record<string, string> = {};
  for (const c of COMMANDS) { out[`docs/site/reference/cli/${c.name}.md`] = referencePage(c); out[`docs/man/${c.name === 'centcom' ? 'centcom' : `centcom-${c.name}`}.1`] = manPage(c, v, CONTRACT_VERSION); }
  out['docs/site/reference/cli/index.md'] = ['<!-- Generated. Do not edit. -->', '# Command line', '', ...COMMANDS.map((c) => `- [${c.name}](./${c.name}.md): ${c.summary}`), ''].join('\n');
  out['docs/site/reference/env.md'] = envPage(); out['docs/site/reference/exit-codes.md'] = exitPage(); out['docs/site/guide/privacy-relay.md'] = privacyList(); return out;
}
export function check(): string[] { const bad: string[] = []; const want = generated(); for (const [p, text] of Object.entries(want)) { const f = join(ROOT, p); if (!existsSync(f) || readFileSync(f, 'utf8') !== text) bad.push(p); } for (const dir of ['docs/site/reference/cli', 'docs/man']) { const d = join(ROOT, dir); if (existsSync(d)) for (const f of readdirSync(d)) if (!(`${dir}/${f}` in want)) bad.push(`${dir}/${f} (no longer generated)`); } return bad; }
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) { const bad = check(); if (bad.length) { console.error('Out of date (run pnpm docs:gen):\n' + bad.map((b) => '  ' + b).join('\n')); process.exit(1); } console.log('generated docs up to date'); }
  else { for (const [p, text] of Object.entries(generated())) { const f = join(ROOT, p); mkdirSync(join(f, '..'), { recursive: true }); writeFileSync(f, text); } for (const dir of ['docs/site/reference/cli', 'docs/man']) { const d = join(ROOT, dir); for (const f of readdirSync(d)) if (!(`${dir}/${f}` in generated())) rmSync(join(d, f)); } console.log('wrote the reference and man pages'); }
}
