/** Writes docs/agent-states.md from the same table the state machine uses. Run: pnpm exec tsx tools/docs/states-doc.ts [--check] */
import { readFileSync, writeFileSync } from 'node:fs';
import { AGENT_WIRE_STATES } from '../../packages/protocol/src/index.ts';
import { DWELL_MS, EVENT_STATE_TABLE, SLEEP_MS, THINKING_HARD_MS } from '../../packages/agent/src/state/mapping.ts';

const rows = EVENT_STATE_TABLE.map((r) => `| \`${r.input}\` | \`${r.state}\` | ${r.note ?? ''} |`).join('\n');
const doc = `# Agent states

<!-- Generated by tools/docs/states-doc.ts from packages/agent/src/state/mapping.ts. Do not edit. -->

The state machine (\`packages/agent/src/state\`) turns the normalised engine events and runner signals into the contract's state names (CT-STATE-MAP). It works the same for Claude Code and Codex because it never sees raw CLI output.

## Event to state

| Input | State | Notes |
|---|---|---|
${rows}

When several tools are open at once the newest one is shown; when it closes the previous one is shown, then \`thinking\`. Tool kinds come from the tool name (and, for shell tools, the first word of the command: \`cat\` is a read, \`rg\` a search, \`rm\` a delete).

## Timing

${Object.entries(DWELL_MS).map(([s, ms]) => `- \`${s}\`: ${ms} ms, then back to the work state or \`idle\``).join('\n')}
- \`thinking\` becomes \`thinking-hard\` after ${THINKING_HARD_MS / 1000} s without engine output.
- \`idle\` becomes \`sleeping\` after ${SLEEP_MS / 60000} min; a new turn wakes it.

## What goes on the wire

Only the contract's agent-level states are sent in \`agent.state\`: ${AGENT_WIRE_STATES.map((s) => `\`${s}\``).join(', ')}. \`prompt-received\` and \`sleeping\` are real contract state names but are not in that list, so they only go to the local UI. At most 2 frames per agent per second, never the same state twice in a row, payload \`{agent_id, state, since}\` only.

Client-local states (connectivity, account, provider, limits, social) are never produced here. Cap and rate-limit errors from the engine are passed to the UI as a hint while the wire state stays \`warning\`.
`;
if (process.argv.includes('--check')) { if (readFileSync('docs/agent-states.md', 'utf8') !== doc) { console.error('docs/agent-states.md is stale: run pnpm exec tsx tools/docs/states-doc.ts'); process.exit(1); } } else writeFileSync('docs/agent-states.md', doc);
