import { Link, createRoute, useNavigate, useParams } from '@tanstack/react-router';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { rootRoute } from '../app/root.js';
import type { RouteModule } from '../app/types.js';
import { useHttp } from '../lib/http-context.js';
import { Banner, Button, Card, EmptyState, Input, Skeleton, Table, useToast } from '../ui/index.js';
import { ConfirmByName, MembersTable, SeatBanner, useRetryAfter } from './components.js';
import { InviteDialog, SettingsForm, deleteWorkspace, errStatus, inviteLink, invitesPager, membersPager, removeMember, renameWorkspace, revokeInvite, transferOwnership, whoAmI, type InviteInput, type Member, type WorkspaceSettings } from './data.js';
import { REASON, can, type WorkspaceRole } from './rbac.js';

interface Ws { id: string; name: string; role: WorkspaceRole; member_count?: number }
export function useWs(id: string): { ws?: Ws; error?: unknown; reload(): void } {
  const http = useHttp(); const nav = useNavigate(); const { toast } = useToast(); const [ws, setWs] = useState<Ws>(); const [error, setError] = useState<unknown>(); const [n, setN] = useState(0);
  useEffect(() => { let on = true; http.call('getWorkspace', { id }).then((r) => { if (on) setWs(r.data as Ws); }).catch((e: unknown) => { if (!on) return; if (errStatus(e) === 404) { toast('info', 'That workspace no longer exists.'); void nav({ to: '/workspaces' as never }); } else setError(e); }); return () => { on = false; }; }, [http, id, n, nav, toast]);
  return { ws, error, reload: () => setN((x) => x + 1) };
}
function Workspaces(): React.JSX.Element {
  const http = useHttp(); const nav = useNavigate(); const { toast } = useToast(); const [rows, setRows] = useState<Ws[]>(); const [name, setName] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void http.listPage('listWorkspaces', {}).then((p) => setRows(p.data as Ws[])).catch(() => setRows([])); }, [http]);
  const create = (): void => { if (busy || !name.trim()) return; setBusy(true); void http.call('createWorkspace', { body: { name: name.trim() } }).then((r) => nav({ to: `/w/${(r.data as Ws).id}` as never })).catch(() => toast('danger', 'The workspace could not be created.')).finally(() => setBusy(false)); };
  return <Card title="Workspaces">{rows === undefined ? <Skeleton lines={3} /> : rows.length ? <Table caption="Your workspaces" rows={rows} rowKey={(w) => w.id} columns={[{ key: 'n', header: 'Name', cell: (w) => <Link to={`/w/${w.id}` as never}>{w.name}</Link> }, { key: 'r', header: 'Your role', cell: (w) => w.role }]} /> : <EmptyState title="No workspaces yet">Create one to invite your team.</EmptyState>}<form onSubmit={(e) => { e.preventDefault(); create(); }}><Input label="New workspace" value={name} onChange={(e) => setName(e.target.value)} maxLength={80} /><Button variant="primary" type="submit" disabledReason={name.trim() ? undefined : 'Give it a name first.'}>Create workspace</Button></form></Card>;
}
function Overview(): React.JSX.Element { const { wsp } = useParams({ strict: false }) as { wsp: string }; const { ws } = useWs(wsp); return ws ? <Card title={ws.name}><p>Your role: {ws.role}. {ws.member_count ?? '?'} members.</p><nav aria-label="Workspace"><Link to={`/w/${wsp}/members` as never}>Members</Link> · <Link to={`/w/${wsp}/projects` as never}>Projects</Link> · <Link to={`/w/${wsp}/settings` as never}>Settings</Link></nav></Card> : <Skeleton lines={2} />; }
export function Members(): React.JSX.Element {
  const { wsp } = useParams({ strict: false }) as { wsp: string }; const http = useHttp(); const nav = useNavigate(); const { toast } = useToast(); const { ws } = useWs(wsp);
  const pager = useMemo(() => membersPager(http, wsp), [http, wsp]); const invites = useMemo(() => invitesPager(http, wsp), [http, wsp]); const [, bump] = useState(0); const [me, setMe] = useState('');
  const load = useCallback(() => { void pager.loadMore().finally(() => bump((x) => x + 1)); }, [pager]); const loadInv = useCallback(() => { void invites.loadMore().finally(() => bump((x) => x + 1)); }, [invites]);
  useEffect(() => { load(); loadInv(); void whoAmI(http).then((id) => setMe(id ?? '')); }, [load, loadInv, http]);
  const refresh = (): void => { pager.reset(); load(); }; const refreshInv = (): void => { invites.reset(); loadInv(); };
  const [dlg, setDlg] = useState<InviteDialog>(); const [email, setEmail] = useState(''); const [role, setRole] = useState<InviteInput['role']>('member'); const [msg, setMsg] = useState<string>(); const [link, setLink] = useState<string>(); const [noSeats, setNoSeats] = useState(false); const [target, setTarget] = useState<{ kind: 'remove' | 'transfer'; m: Member }>(); const retry = useRetryAfter();
  const reset = (): void => { setDlg(undefined); setMsg(undefined); setLink(undefined); };
  const invite = (asLink: boolean): void => { const d = dlg ?? new InviteDialog(http, wsp); setDlg(d); void d.create({ ...(asLink ? {} : { email }), role }).then((r) => { if (r.ok) { setMsg(asLink ? 'Link created.' : 'Invite sent.'); setLink(inviteLink(r.invite)); toast('success', asLink ? 'Link created.' : 'Invite sent.'); refreshInv(); } else if (r.reason === 'no_seats') setNoSeats(true); else if (r.reason === 'rate_limited') retry.arm(r.retryAfterS ?? 1); else setMsg(r.reason === 'forbidden' ? 'You are not allowed to invite people.' : 'The invite could not be sent.'); }); };
  const can_ = can(ws?.role, 'invite'); const why = !can_ ? REASON.invite : retry.reason;
  const done = (): void => { setTarget(undefined); refresh(); };
  const fail = (r: { reason: string; retryAfterS?: number }): void => { toast('danger', r.reason === 'rate_limited' ? `Too many requests. Try again in ${r.retryAfterS ?? 1}s.` : r.reason === 'forbidden' ? 'You are not allowed to do that.' : 'That could not be done.'); };
  return <Card title="Members">{noSeats ? <SeatBanner billingHref={`/w/${wsp}/billing`} /> : null}
    <MembersTable members={pager.items} me={me} myRole={ws?.role} http={http} ws={wsp} onChanged={refresh} onRemove={(m) => setTarget({ kind: 'remove', m })} onTransfer={(m) => setTarget({ kind: 'transfer', m })} />
    {pager.hasMore ? <Button onClick={load} disabledReason={pager.loading ? 'Loading…' : undefined}>Load more</Button> : null}
    <h3>Invite people</h3>
    <form onSubmit={(e) => { e.preventDefault(); invite(false); }}><Input label="Email" type="email" value={email} onChange={(e) => { setEmail(e.target.value); reset(); }} /><label className="cc-label" htmlFor="inv-role">Role</label><select id="inv-role" className="cc-input" value={role} onChange={(e) => { setRole(e.target.value as InviteInput['role']); reset(); }}>{(ws?.role === 'owner' ? ['admin', 'member', 'billing', 'guest'] : ['member', 'billing', 'guest']).map((r) => <option key={r} value={r}>{r}</option>)}</select>
      <Button variant="primary" type="submit" disabledReason={why ?? (!email ? 'Enter an email first.' : undefined)}>Send invite</Button><Button type="button" disabledReason={why} onClick={() => invite(true)}>Create a link</Button>{msg ? <p role="status">{msg}</p> : null}{link ? <p>Link: <code>{link}</code></p> : null}</form>
    {invites.items.length ? <Table caption="Open invites" rows={invites.items} rowKey={(i) => i.id} columns={[{ key: 'e', header: 'Invitee', cell: (i) => i.email ?? 'Link invite' }, { key: 'r', header: 'Role', cell: (i) => i.role }, { key: 's', header: 'Status', cell: (i) => i.status }, { key: 'x', header: 'Expires', cell: (i) => i.expires_at.slice(0, 10) }, { key: 'a', header: 'Actions', cell: (i) => (can_ && i.status === 'pending' ? <Button variant="ghost" onClick={() => void revokeInvite(http, i.id).then((r) => (r.ok ? refreshInv() : fail(r)))}>Revoke</Button> : null) }]} /> : null}
    {invites.hasMore ? <Button onClick={loadInv}>More invites</Button> : null}
    <ConfirmByName open={target?.kind === 'remove'} verb={target?.m.user?.id === me ? 'Leave workspace' : 'Remove member'} name={ws?.name ?? ''} onClose={() => setTarget(undefined)} onConfirm={() => void removeMember(http, wsp, target!.m.id).then((r) => (r.ok ? done() : fail(r)))} />
    <ConfirmByName open={target?.kind === 'transfer'} verb="Transfer ownership" name={ws?.name ?? ''} detail="The new owner can delete the workspace. You become an admin." onClose={() => setTarget(undefined)} onConfirm={() => void transferOwnership(http, wsp, target!.m.id).then((r) => { if (r.ok) { done(); void nav({ to: `/w/${wsp}` as never }); } else fail(r); })} /></Card>;
}
function Projects(): React.JSX.Element { const { wsp } = useParams({ strict: false }) as { wsp: string }; const http = useHttp(); const [rows, setRows] = useState<{ id: string; name: string; repo?: string }[]>(); useEffect(() => { void http.listPage('listProjects', { id: wsp }).then((p) => setRows(p.data as never)).catch(() => setRows([])); }, [http, wsp]); return <Card title="Projects">{rows === undefined ? <Skeleton lines={2} /> : rows.length ? <Table caption="Projects" rows={rows} rowKey={(p) => p.id} columns={[{ key: 'n', header: 'Name', cell: (p) => p.name }, { key: 'r', header: 'Repository', cell: (p) => p.repo ?? '' }]} /> : <EmptyState title="No projects yet">Projects appear when someone hosts a session from a repository.</EmptyState>}</Card>; }
export function Settings(): React.JSX.Element {
  const { wsp } = useParams({ strict: false }) as { wsp: string }; const http = useHttp(); const nav = useNavigate(); const { toast } = useToast(); const { ws, reload } = useWs(wsp); const form = useMemo(() => new SettingsForm(http, wsp), [http, wsp]); const [v, setV] = useState<WorkspaceSettings>(); const [conflict, setConflict] = useState(false); const [del, setDel] = useState(false); const [name, setName] = useState<string>(); const retry = useRetryAfter();
  useEffect(() => { let on = true; void form.load().then(() => { if (on) setV(form.value); }); return () => { on = false; }; }, [form]); const allowed = can(ws?.role, 'update_settings'); const why = !allowed ? REASON.update_settings : retry.reason;
  const bad = (r: { reason: string; retryAfterS?: number }): void => { if (r.reason === 'rate_limited') retry.arm(r.retryAfterS ?? 1); else toast('danger', r.reason === 'forbidden' ? 'You are not allowed to change that.' : 'That could not be saved.'); };
  const save = (): void => { if (!v) return; void form.save(v).then((r) => { if (r.ok) toast('success', 'Saved.'); else if (r.reason === 'changed_elsewhere') setConflict(true); else bad(r); }); };
  return <Card title="Settings">{conflict ? <Banner tone="warning" title="Changed elsewhere">Someone else changed these settings. <Button onClick={() => void form.reapply().then((r) => { if (r.ok) { setConflict(false); setV(form.value); toast('success', 'Saved.'); } else bad(r); })}>Refresh and reapply my changes</Button></Banner> : null}
    <form onSubmit={(e) => { e.preventDefault(); const n = (name ?? ws?.name ?? '').trim(); if (n) void renameWorkspace(http, wsp, n).then((r) => { if (r.ok) { toast('success', 'Renamed.'); reload(); } else bad(r); }); }}><Input label="Workspace name" value={name ?? ws?.name ?? ''} onChange={(e) => setName(e.target.value)} maxLength={80} disabled={!allowed} /><Button type="submit" disabledReason={why}>Rename</Button></form>
    {v ? <form onSubmit={(e) => { e.preventDefault(); save(); }}><label className="cc-label" htmlFor="aa">Default approvals</label><select id="aa" className="cc-input" value={v.auto_approve} disabled={!allowed} onChange={(e) => setV({ ...v, auto_approve: e.target.value as WorkspaceSettings['auto_approve'] })}><option value="ask">Ask the host</option><option value="trusted">Trusted members</option><option value="everyone">Everyone</option></select>
      <label><input type="checkbox" checked={v.share_history} disabled={!allowed} onChange={(e) => setV({ ...v, share_history: e.target.checked })} /> Share history with new members</label>
      <Input label="Keep history for (days, empty for the plan default)" type="number" min={1} max={3650} value={v.history_retention_days ?? ''} disabled={!allowed} onChange={(e) => setV({ ...v, history_retention_days: e.target.value === '' ? null : Math.max(1, Math.min(3650, Number(e.target.value))) })} />
      <Button variant="primary" type="submit" disabledReason={why}>Save settings</Button></form> : <Skeleton lines={3} />}
    <h3>Delete workspace</h3><Button variant="danger" onClick={() => setDel(true)} disabledReason={can(ws?.role, 'delete_workspace') ? undefined : REASON.delete_workspace}>Delete workspace…</Button>
    <ConfirmByName open={del} verb="Delete workspace" name={ws?.name ?? ''} detail="Billing winds down over 7 days. Sessions and history are removed." onClose={() => setDel(false)} onConfirm={() => void deleteWorkspace(http, wsp).then((r) => (r.ok ? nav({ to: '/workspaces' as never }) : bad(r)))} /></Card>;
}
const r = (path: string, component: () => React.JSX.Element) => createRoute({ getParentRoute: () => rootRoute, path, component });
export const routeModule: RouteModule = { routes: [r('/workspaces', Workspaces), r('/w/$wsp', Overview), r('/w/$wsp/members', Members), r('/w/$wsp/projects', Projects), r('/w/$wsp/settings', Settings)], nav: [{ id: 'workspaces', labelKey: 'nav.workspaces', to: '/workspaces', icon: 'people' }] };
export default routeModule;
