import { describe, expect, it } from 'vitest';
import { BRIDGE_MS, COLLAPSED_STATE, MAX_ANIMATING, MIN_DWELL, MascotScheduler, StateGate } from '../../src/mascot/scheduler.js';

const clock = () => { let t = 0; const q: { at: number; fn: () => void; h: number }[] = []; let id = 0; return { now: () => t, setTimeout: (fn: () => void, ms: number) => { const h = ++id; q.push({ at: t + ms, fn, h }); return h; }, clearTimeout: (h: unknown) => { const i = q.findIndex((x) => x.h === h); if (i >= 0) q.splice(i, 1); }, advance(ms: number) { const end = t + ms; for (;;) { q.sort((a, b) => a.at - b.at); const n = q[0]; if (!n || n.at > end) break; q.shift(); t = n.at; n.fn(); } t = end; } }; };
describe('at most six move (acceptance 3, 8)', () => {
  it('7 mounted: the first 6 animate and the 7th holds frame 0; unmounting one lets the 7th start', () => { const s = new MascotScheduler(); const on: Record<string, boolean> = {}; const offs = Array.from({ length: 7 }, (_, i) => s.register(`m${i}`, (a) => { on[`m${i}`] = a; })); expect(Object.values(on).filter(Boolean)).toHaveLength(MAX_ANIMATING); expect(on.m6).toBe(false); offs[2]!(); expect(on.m6).toBe(true); expect(s.animating()).toHaveLength(6); });
  it('an off-screen canvas does not use a slot, a hidden tab stops everything and a returning tab restarts it', () => { const s = new MascotScheduler(); const on: Record<string, boolean> = {}; for (let i = 0; i < 8; i++) s.register(`m${i}`, (a) => { on[`m${i}`] = a; }); s.setVisible('m0', false); expect(on.m0).toBe(false); expect(on.m6).toBe(true); expect(on.m7).toBe(false); s.setPageHidden(true); expect(Object.values(on).some(Boolean)).toBe(false); expect(s.animating()).toEqual([]); s.setPageHidden(false); expect(Object.values(on).filter(Boolean)).toHaveLength(6); s.setVisible('m0', true); expect(on.m0).toBe(true); });
  it('a smaller cap is honoured and listeners hear only real changes', () => { const s = new MascotScheduler(2); let calls = 0; for (let i = 0; i < 3; i++) s.register(`m${i}`, () => void calls++); const c = calls; s.setVisible('m0', true); s.setPageHidden(false); expect(calls).toBe(c); expect(s.animating()).toEqual(['m0', 'm1']); });
});
describe('changing the shown state (acceptance 4)', () => {
  it('a state is shown at once the first time, and a change within 600 ms waits for the dwell', () => { const c = clock(); const shown: string[] = []; const g = new StateGate(c, (s) => shown.push(s)); g.request('idle'); expect(shown).toEqual(['idle']); c.advance(100); g.request('editing-file'); expect(shown).toEqual(['idle']); c.advance(MIN_DWELL - 101); expect(shown).toEqual(['idle']); c.advance(1); expect(shown).toEqual(['idle', 'editing-file']); c.advance(700); g.request('idle'); expect(shown.at(-1)).toBe('idle'); });
  it('changes that are far enough apart are each shown, after the dwell', () => { const c = clock(); const shown: string[] = []; const g = new StateGate(c, (s) => shown.push(s)); g.request('idle'); c.advance(50); g.request('thinking'); c.advance(2000); g.request('searching'); c.advance(100); g.request('planning'); c.advance(1000); expect(shown).toEqual(['idle', 'thinking', 'searching', 'planning']); });
  it('three changes in two seconds collapse into one tool-running', () => { const c = clock(); const shown: string[] = []; const g = new StateGate(c, (s) => shown.push(s)); g.request('reading-file'); c.advance(200); g.request('editing-file'); c.advance(200); g.request('running-command'); c.advance(1000); expect(shown).toEqual(['reading-file', COLLAPSED_STATE]); expect(g.shown).toBe(COLLAPSED_STATE); c.advance(3000); g.request('idle'); expect(shown.at(-1)).toBe('idle'); });
  it('the same state again changes nothing, and dispose stops a waiting change', () => { const c = clock(); const shown: string[] = []; const g = new StateGate(c, (s) => shown.push(s)); g.request('idle'); g.request('idle'); c.advance(1000); expect(shown).toEqual(['idle']); c.advance(2500); g.request('thinking'); c.advance(10); g.request('searching'); g.dispose(); c.advance(2000); expect(shown).toEqual(['idle', 'thinking']); expect(BRIDGE_MS).toBeLessThanOrEqual(200); });
});
