import { describe, expect, it } from 'vitest';
import { engineSettings, sandboxSettings } from '../../src/sandbox/index.js';

const base = { root: '/work/proj', network: 'allow' as const, bypassOptIn: false };
const MODES = ['ask', 'accept-edits', 'plan', 'auto-low-risk', 'bypass'] as const;
describe('engine settings (golden argv)', () => {
  it('claude-code', () => { expect(engineSettings('plan', 'claude-code', base).argv).toEqual(['--permission-mode', 'plan']); expect(engineSettings('ask', 'claude-code', base).argv).toEqual(['--permission-mode', 'default']); expect(engineSettings('accept-edits', 'claude-code', base).argv).toEqual(['--permission-mode', 'acceptEdits']); expect(engineSettings('auto-low-risk', 'claude-code', base).argv).toEqual(['--permission-mode', 'default']); expect(engineSettings('bypass', 'claude-code', { ...base, bypassOptIn: true }).argv).toEqual(['--permission-mode', 'bypassPermissions']); });
  it('codex', () => { expect(engineSettings('accept-edits', 'codex', base).argv).toEqual(['--sandbox', 'workspace-write', '--ask-for-approval', 'on-request']); expect(engineSettings('ask', 'codex', base).argv).toEqual(['--sandbox', 'workspace-write', '--ask-for-approval', 'untrusted']); expect(engineSettings('plan', 'codex', base).argv).toEqual(['--sandbox', 'read-only', '--ask-for-approval', 'untrusted']); expect(engineSettings('bypass', 'codex', { ...base, bypassOptIn: true }).argv).toEqual(['--sandbox', 'danger-full-access', '--ask-for-approval', 'never']); });
  it('the app-server equivalents', () => { expect(engineSettings('accept-edits', 'codex', base).appServer).toEqual({ approvalPolicy: 'on-request', sandboxPolicy: { type: 'workspaceWrite', writableRoots: ['/work/proj'], networkAccess: true } }); expect(engineSettings('plan', 'codex', base).appServer).toEqual({ approvalPolicy: 'untrusted', sandboxPolicy: { type: 'readOnly' } }); });
});
describe('acceptance 7: bypass needs the opt-in', () => {
  it.each(['claude-code', 'codex'] as const)('%s without opt-in gives the ask settings and a note', (engine) => { const r = engineSettings('bypass', engine, base); expect(r.argv).toEqual(engineSettings('ask', engine, base).argv); expect(r.argv.join(' ')).not.toMatch(/bypassPermissions|danger-full-access|never/); expect(r.notes).toContain('bypass_requires_opt_in'); });
  it('no combination of mode, engine and opt-in gives bypass without the opt-in', () => { for (const m of MODES) for (const e of ['claude-code', 'codex'] as const) { const r = engineSettings(m, e, { ...base, bypassOptIn: false }); expect(JSON.stringify(r)).not.toMatch(/bypassPermissions|danger-full-access|"never"/); } });
  it('an unknown mode or engine is safe and never throws', () => { expect(engineSettings('nope' as never, 'codex', base).argv).toEqual(engineSettings('ask', 'codex', base).argv); expect(engineSettings('ask', 'other' as never, base).argv).toEqual([]); });
});
describe('acceptance 8: network off', () => {
  it('uses the native option when the CLI has it', () => { const r = engineSettings('ask', 'codex', { ...base, network: 'deny', caps: { codexNetworkOff: true } }); expect(r.argv).toContain('sandbox_workspace_write.network_access=false'); expect(r.notes.join()).not.toMatch(/provider_capability_missing/); expect((r.appServer!.sandboxPolicy as { networkAccess: boolean }).networkAccess).toBe(false); });
  it('says so, and does not pretend, when it has not', () => { const r = engineSettings('ask', 'codex', { ...base, network: 'deny' }); expect(r.argv.join(' ')).not.toMatch(/network/); expect(r.notes.some((n) => n.startsWith('provider_capability_missing'))).toBe(true); expect(engineSettings('ask', 'claude-code', { ...base, network: 'deny' }).notes.some((n) => n.startsWith('provider_capability_missing'))).toBe(true); });
  it('read-only needs no flag', () => { expect(engineSettings('plan', 'codex', { ...base, network: 'deny' }).notes).toEqual([]); });
  it('extra writable roots are passed only where supported', () => { expect(engineSettings('ask', 'codex', { ...base, extraRoots: ['/tmp/w'], caps: { codexWritableRoots: true } }).argv.join(' ')).toContain('writable_roots=["/tmp/w"]'); expect(engineSettings('ask', 'codex', { ...base, extraRoots: ['/tmp/w'] }).notes[0]).toMatch(/provider_capability_missing/); });
});
describe('sandbox settings', () => { it('lists write roots without duplicates, network and the protected places', () => { const s = sandboxSettings({ root: '/work/proj', tmp: '/tmp/x', extraRoots: ['/work/proj/'] }); expect(s.writeRoots).toEqual(['/work/proj', '/tmp/x']); expect(s.network).toBe('allow'); expect(s.protected.length).toBeGreaterThan(5); expect(sandboxSettings({ root: '/a', network: 'deny' }).network).toBe('deny'); }); });
