import { Link, createRoute } from '@tanstack/react-router';
import React, { useEffect, useMemo, useState } from 'react';
import { rootRoute } from '../app/root.js';
import type { RouteModule } from '../app/types.js';
import { useHttp } from '../lib/http-context.js';
import { readDensity, setDensity, useTheme, type Density } from '../theme/theme.js';
import { Banner, Button, Card, EmptyState, Input, Skeleton, Table, Tabs, useToast } from '../ui/index.js';
import { CATEGORIES, CHANNELS, INBOX_LOCKED, NAME_MAX, QUIET_NOTE, TELEMETRY_TEXT, effective, linkFor, textFor, toggleChannel, unread, validateAccount, validateQuiet, type Channel } from './model.js';
import { inboxPager, listDevices, loadPreferences, markAllRead, markRead, revokeDevice, savePreferences, updateAccount, type Device } from './data.js';
import { PushRegistrar, pushSupported, type PushEnv } from './push.js';
import type { NotificationPreferences } from '@centcom/notify';
import { useRetryAfter } from '../workspace/retry.js';

export function Inbox(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const [only, setOnly] = useState(false); const pager = useMemo(() => inboxPager(http, only), [http, only]); const [, bump] = useState(0); const [readIds, setReadIds] = useState<Set<string>>(new Set());
  const load = (): void => { void pager.loadMore().finally(() => bump((x) => x + 1)); }; useEffect(() => { pager.reset(); load(); }, [pager]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const n = pager.items.filter((i) => !i.read_at).length; if (!only && !pager.hasMore) unread.set(n); }, [pager.items.length, pager.hasMore, only, pager]);
  return <Card title="Notifications"><label><input type="checkbox" checked={only} onChange={(e) => setOnly(e.target.checked)} /> Unread only</label> <Button onClick={() => void markAllRead(http).then((r) => { if (r.ok) setReadIds(new Set(pager.items.map((i) => i.id))); else toast('danger', 'That could not be done.'); })}>Mark all read</Button>
    {pager.items.length === 0 && !pager.loading ? <EmptyState title="Nothing new">You are all caught up.</EmptyState> : <ul aria-label="Notifications" className="cc-list">{pager.items.map((n) => { const t = textFor(n); const link = linkFor(n); const isRead = !!n.read_at || readIds.has(n.id); return <li key={n.id}><strong>{isRead ? '' : '● '}{t.title}</strong> <span>{t.body}</span> {link ? <Link to={link as never}>Open</Link> : null} {!isRead ? <Button variant="ghost" onClick={() => void markRead(http, n.id, true).then((r) => { if (r.ok) setReadIds((s) => new Set(s).add(n.id)); else toast('danger', 'That could not be done.'); })}>Mark read</Button> : null}</li>; })}</ul>}
    {pager.hasMore ? <Button onClick={load} disabledReason={pager.loading ? 'Loading…' : undefined}>Load more</Button> : null}</Card>;
}
export function NotificationSettings(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const [p, setP] = useState<NotificationPreferences>(); const [etag, setEtag] = useState<string>(); const [err, setErr] = useState<string>(); const [pushMsg, setPushMsg] = useState<string>(); const retry = useRetryAfter();
  const env = useMemo<PushEnv>(() => ({ Notification: typeof Notification !== 'undefined' ? (Notification as never) : undefined, serviceWorker: typeof navigator !== 'undefined' && 'serviceWorker' in navigator ? (navigator.serviceWorker as never) : undefined, hasPush: typeof window !== 'undefined' && 'PushManager' in window }), []); const reg = useMemo(() => new PushRegistrar(env, http), [env, http]);
  useEffect(() => { void loadPreferences(http).then((r) => { setP(r.prefs); setEtag(r.etag); }).catch(() => setErr('Your settings could not be loaded.')); }, [http]);
  if (err) return <Banner tone="danger">{err}</Banner>; if (!p) return <Skeleton lines={4} />;
  const save = (next: NotificationPreferences): void => { const bad = validateQuiet(next.quiet_hours); if (bad) { setErr(undefined); toast('warning', bad); return; } setP(next); void savePreferences(http, next, etag, () => next).then((r) => { if (r.ok) { setP(r.prefs); setEtag(r.etag); if (r.notice) toast('info', r.notice); } else if (r.reason === 'rate_limited') retry.arm(r.retryAfterS ?? 1); else toast('danger', 'Your settings could not be saved.'); }); };
  return <Card title="Notification settings"><table className="cc-table"><caption className="cc-vh">Channels by category</caption><thead><tr><th scope="col">Category</th>{CHANNELS.map((c) => <th key={c} scope="col">{c}</th>)}</tr></thead><tbody>{CATEGORIES.map((cat) => <tr key={cat}><th scope="row">{cat.replace(/_/g, ' ')}</th>{CHANNELS.map((ch: Channel) => { const locked = ch === 'inbox' && INBOX_LOCKED.has(cat); return <td key={ch}><input type="checkbox" aria-label={`${cat.replace(/_/g, ' ')}, ${ch}`} checked={effective(p, cat, ch)} disabled={locked || (ch === 'push' && !pushSupported(env))} onChange={(e) => save(toggleChannel(p, cat, ch, e.target.checked))} /></td>; })}</tr>)}</tbody></table>
    {!pushSupported(env) ? <p className="cc-help">This browser cannot receive push notifications, so that column is off.</p> : null}
    <h3>Quiet hours</h3><label><input type="checkbox" checked={p.quiet_hours.enabled} onChange={(e) => save({ ...p, quiet_hours: { ...p.quiet_hours, enabled: e.target.checked } })} /> Hold notifications</label> <Input label="From" value={p.quiet_hours.start} onChange={(e) => setP({ ...p, quiet_hours: { ...p.quiet_hours, start: e.target.value } })} onBlur={() => save(p)} /><Input label="Until" value={p.quiet_hours.end} onChange={(e) => setP({ ...p, quiet_hours: { ...p.quiet_hours, end: e.target.value } })} onBlur={() => save(p)} /><p className="cc-help">{QUIET_NOTE}</p>
    {pushSupported(env) ? <div><Button onClick={() => void reg.enable({ fromClick: true }).then((r) => setPushMsg(r.ok ? 'Push is on.' : r.reason === 'denied' ? 'The browser did not allow notifications.' : 'Push could not be turned on.'))}>Turn on push in this browser</Button> <Button onClick={() => void reg.disable().then((ok) => setPushMsg(ok ? 'Push is off.' : 'Push could not be turned off.'))}>Turn off push</Button>{pushMsg ? <p role="status">{pushMsg}</p> : null}</div> : null}
    {retry.reason ? <p role="status">{retry.reason}</p> : null}</Card>;
}
export function Account(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const [name, setName] = useState(''); const [locale, setLocale] = useState('en'); const [tele, setTele] = useState(false); const [error, setError] = useState<string>(); const [loaded, setLoaded] = useState(false);
  useEffect(() => { void http.call('getMe', {}).then((r) => { const u = (r.data as { user: { display_name?: string; locale?: string; telemetry?: boolean } }).user; setName(u.display_name ?? ''); setLocale(u.locale ?? 'en'); setTele(!!u.telemetry); setLoaded(true); }).catch(() => setLoaded(true)); }, [http]);
  if (!loaded) return <Skeleton lines={3} />;
  return <Card title="Account"><form onSubmit={(e) => { e.preventDefault(); const bad = validateAccount({ display_name: name, locale }); setError(bad); if (!bad) void updateAccount(http, { display_name: name.trim(), locale }).then((r) => (r.ok ? toast('success', 'Saved.') : toast('danger', 'That could not be saved.'))); }}><Input label="Display name" value={name} maxLength={NAME_MAX + 10} error={error?.includes('name') ? error : undefined} onChange={(e) => setName(e.target.value)} /><Input label="Language" value={locale} error={error?.includes('language') ? error : undefined} onChange={(e) => setLocale(e.target.value)} /><Button variant="primary" type="submit">Save</Button></form>
    <h3>Usage statistics</h3><p>{TELEMETRY_TEXT}</p><label><input type="checkbox" checked={tele} onChange={(e) => { const v = e.target.checked; setTele(v); void updateAccount(http, { telemetry: v }).then((r) => { if (!r.ok) { setTele(!v); toast('danger', 'That could not be saved.'); } }); }} /> Share anonymous usage statistics</label></Card>;
}
export function Appearance(): React.JSX.Element { const { theme, set } = useTheme(); const [d, setD] = useState<Density>(readDensity()); return <Card title="Appearance"><label className="cc-label" htmlFor="th">Theme</label><select id="th" className="cc-input" value={theme} onChange={(e) => set(e.target.value as never)}><option value="auto">Match my system</option><option value="dark">Dark</option><option value="light">Light</option></select><label className="cc-label" htmlFor="dn">Density</label><select id="dn" className="cc-input" value={d} onChange={(e) => { const v = e.target.value as Density; setD(v); setDensity(v); }}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Card>; }
export function Devices(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const [rows, setRows] = useState<Device[]>(); const load = (): void => { void listDevices(http).then(setRows).catch(() => setRows([])); }; useEffect(load, [http]); // eslint-disable-line react-hooks/exhaustive-deps
  return <Card title="Devices">{rows === undefined ? <Skeleton lines={2} /> : <Table caption="Signed-in devices" rows={rows} rowKey={(d) => d.id} columns={[{ key: 'n', header: 'Name', cell: (d) => `${d.name}${d.current ? ' (this one)' : ''}` }, { key: 'p', header: 'Platform', cell: (d) => d.platform ?? '' }, { key: 's', header: 'Last seen', cell: (d) => (d.last_seen_at ?? d.created_at).slice(0, 10) }, { key: 'a', header: 'Actions', cell: (d) => (d.revoked_at ? 'revoked' : <Button variant="ghost" disabledReason={d.current ? 'Sign out to remove this device.' : undefined} onClick={() => void revokeDevice(http, d.id).then((r) => (r.ok ? load() : toast('danger', 'That could not be done.')))}>Revoke</Button>) }]} />}</Card>;
}
void Tabs;
const r = (path: string, component: () => React.JSX.Element) => createRoute({ getParentRoute: () => rootRoute, path, component });
export const routeModule: RouteModule = { routes: [r('/notifications', Inbox), r('/settings/notifications', NotificationSettings), r('/settings/account', Account), r('/settings/appearance', Appearance), r('/settings/devices', Devices)], nav: [{ id: 'settings', labelKey: 'nav.settings', to: '/settings/account', icon: 'settings' }] };
export default routeModule;
