/** A sentence for every state, so nothing depends on colour, a glyph or the mascot. `{files}` becomes "3 files" or "a file". */
export const STATE_TEXT: Record<string, string> = {
  'approved': 'Cento got your approval and is carrying on',
  'asking-question': 'Cento has a question for you',
  'auth-required': 'You need to sign in before Cento can continue',
  'awaiting-approval': 'Waiting for your approval',
  'away': 'You are away, Cento is waiting',
  'background-task': 'Cento is running a task in the background',
  'celebrate': 'Cento finished and it went well',
  'ci-fail': 'The checks failed',
  'ci-pass': 'The checks passed',
  'ci-running': 'The checks are running',
  'compacting': 'Cento is shortening the conversation to make room',
  'context-full': 'The conversation is almost full',
  'cost-alert': 'The cost is close to your budget',
  'crash': 'Something went wrong and Cento stopped',
  'creating-file': 'Cento is creating {files}',
  'deleting-file': 'Cento is deleting {files}',
  'denied': 'The action was declined',
  'deploying': 'Cento is deploying',
  'editing-file': 'Cento is editing {files}',
  'empty': 'There is nothing here yet',
  'error': 'Something went wrong',
  'first-run': 'Welcome to Centcom',
  'handoff': 'The session is being handed over',
  'high-five': 'Your teammate and Cento finished a task together',
  'host-session': 'You are hosting this session',
  'idle': 'Cento is idle',
  'listening': 'Cento is listening',
  'merge-conflict': 'There is a merge conflict',
  'message-queued': 'Your message is queued',
  'no-results': 'Nothing was found',
  'offline': 'You are offline',
  'online': 'You are back online',
  'pair-working': 'You and a teammate are working together',
  'planning': 'Cento is making a plan',
  'pr-merged': 'The pull request was merged',
  'pr-open': 'A pull request is open',
  'prompt-received': 'Cento received your message',
  'provider-auth-required': 'You need to sign in to the coding tool',
  'provider-cap-reached': 'The coding tool says its usage limit was reached',
  'provider-policy-blocked': 'The coding tool is blocked by its policy',
  'quota-reached': 'The monthly quota is reached',
  'rate-limited': 'Requests are being limited, Cento will retry',
  'reading-file': 'Cento is reading {files}',
  'ready': 'Cento is ready',
  'reconnecting': 'Reconnecting',
  'running-command': 'Cento is running a command',
  'saving': 'Cento is saving',
  'searching': 'Cento is searching',
  'session-expired': 'Your session expired, sign in again',
  'sleeping': 'Cento is asleep',
  'streaming': 'Cento is writing an answer',
  'sub-agent': 'A helper agent is working',
  'success': 'It worked',
  'teammate-joins': 'A teammate joined',
  'teammate-leaves': 'A teammate left',
  'teammate-typing': 'A teammate is typing',
  'tests-fail': 'The tests failed',
  'tests-pass': 'The tests passed',
  'thinking': 'Cento is thinking',
  'thinking-hard': 'Cento is thinking hard',
  'tool-running': 'Cento is using a tool',
  'update-available': 'A Centcom update is available',
  'warning': 'There is a warning',
  'welcome-teammate': 'Cento welcomes your teammate',
};
/** States that stop the work until the person acts: these are announced as errors. */
export const BLOCKING = new Set(['auth-required', 'provider-auth-required', 'session-expired', 'quota-reached', 'provider-cap-reached', 'provider-policy-blocked', 'crash', 'error']);
export function describeState(state: string, ctx: { count?: number; owner?: string } = {}): string {
  const t = STATE_TEXT[state]; if (!t) return 'Cento is working';
  const files = ctx.count === undefined ? 'a file' : ctx.count === 1 ? 'a file' : `${ctx.count} files`; const text = t.replace('{files}', files);
  return ctx.owner ? text.replace(/^Cento /, `${ctx.owner}'s Cento `) : text;
}
