/** Generates packages/protocol/src/generated from contracts/. Deterministic: same input, same bytes.
 *    pnpm --filter @centcom/protocol gen            write
 *    pnpm --filter @centcom/protocol gen --check    exit 1 if the committed output is stale
 *    pnpm --filter @centcom/protocol gen --out dir  write somewhere else */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse as parseYaml } from 'yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..'); const CONTRACTS = join(ROOT, 'contracts');
const args = process.argv.slice(2); const check = args.includes('--check');
const outDir = resolve(args.includes('--out') ? args[args.indexOf('--out') + 1]! : join(HERE, '../src/generated'));
const BANNER = `// GENERATED by packages/protocol/scripts/gen.ts from contracts/ (contract %V). Do not edit.\n// Regenerate: pnpm --filter @centcom/protocol gen\n`;

type J = Record<string, any>;
const readJson = (p: string): J => JSON.parse(readFileSync(p, 'utf8'));
const sortKeys = (v: any): any => (Array.isArray(v) ? v.map(sortKeys) : v && typeof v === 'object' ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sortKeys(v[k])])) : v);

const index = readJson(join(CONTRACTS, 'index.json')); const VERSION: string = index.contract_version;
const banner = BANNER.replace('%V', VERSION);

/* ------------------------------------------------------------------ schemas */
const schemaFiles = readdirSync(join(CONTRACTS, 'schemas')).filter((f) => f.endsWith('.schema.json')).sort();
const schemas: Record<string, J> = Object.fromEntries(schemaFiles.map((f) => [f.replace('.schema.json', ''), readJson(join(CONTRACTS, 'schemas', f))]));
const ROOT_NAMES: Record<string, string> = { entitlements: 'Entitlements', envelope: 'Frame', 'lan-pair': 'LanPair', notification: 'NotificationPayload', problem: 'ProblemJson', 'provider-policy': 'ProviderPolicy', 'release-manifest': 'ReleaseManifest', telemetry: 'TelemetryBatch', webhook: 'WebhookDelivery', events: 'Events' };
const pascal = (s: string) => s.split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0]!.toUpperCase() + w.slice(1)).join('');

/* ---- JSON Schema subset -> TypeScript (the contracts only use this subset; anything else throws so gaps are noticed) */
const q = (s: string) => JSON.stringify(s);
function ts(s: J, defs: Set<string>): string {
  if (s === true || Object.keys(s).length === 0) return 'unknown';
  if (s.$ref) { const m = /^#\/\$defs\/(.+)$/.exec(s.$ref); if (!m) throw new Error('unsupported $ref ' + s.$ref); defs.add(m[1]!); return pascal(m[1]!); }
  if ('const' in s) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((e: unknown) => JSON.stringify(e)).join(' | ');
  if (s.oneOf || s.anyOf) return (s.oneOf ?? s.anyOf).map((x: J) => `(${ts(x, defs)})`).join(' | ');
  const types: string[] = Array.isArray(s.type) ? s.type : s.type ? [s.type] : s.properties ? ['object'] : [];
  const one = (t: string): string => {
    switch (t) {
      case 'string': return 'string'; case 'number': case 'integer': return 'number'; case 'boolean': return 'boolean'; case 'null': return 'null';
      case 'array': return `Array<${s.items ? ts(s.items, defs) : 'unknown'}>`;
      case 'object': {
        const props = s.properties ?? {}; const req = new Set<string>(s.required ?? []); const lines: string[] = [];
        for (const k of Object.keys(props).sort()) lines.push(`${q(k)}${req.has(k) ? '' : '?'}: ${ts(props[k], defs)};`);
        for (const k of [...req].sort()) if (!(k in props)) lines.push(`${q(k)}: unknown;`);
        if (s.additionalProperties === true || (s.additionalProperties === undefined && !s.properties)) lines.push('[k: string]: unknown;');
        else if (s.additionalProperties && typeof s.additionalProperties === 'object') lines.push(`[k: string]: ${ts(s.additionalProperties, defs)};`);
        return lines.length ? `{ ${lines.join(' ')} }` : 'Record<string, never>';
      }
      default: throw new Error('unsupported type ' + t);
    }
  };
  let out = types.length ? types.map(one).join(' | ') : 'unknown';
  if (s.allOf && !s.allOf.some((x: J) => x.if)) out = [out, ...s.allOf.map((x: J) => ts(x, defs))].join(' & '); // allOf with if/then only adds requirements; the validators enforce those
  return out;
}

function emitTypes(): string {
  const out: string[] = [banner];
  for (const [name, schema] of Object.entries(schemas)) {
    const defs = new Set<string>(); const $defs: J = schema.$defs ?? {};
    out.push(`/* ---- ${name}.schema.json */`);
    if (name !== 'events') out.push(`export type ${ROOT_NAMES[name]} = ${ts({ ...schema, $defs: undefined, allOf: schema.allOf }, defs)};`);
    for (const d of Object.keys($defs).sort()) out.push(`export type ${pascal(name === 'events' ? d : `${name}_${d}`)} = ${ts($defs[d], defs)};`);
  }
  return out.join('\n') + '\n';
}

/* ---- validators: Ajv standalone, strict ("write") and tolerant ("read") */
/** Read side tolerates unknown fields and unknown enum values (CT-VER "Unknown data"). Constants and required fields stay strict. */
function relax(s: any): any {
  if (Array.isArray(s)) return s.map(relax);
  if (!s || typeof s !== 'object') return s;
  const o: J = {};
  for (const [k, v] of Object.entries(s)) {
    if (k === 'additionalProperties' && v === false) { o[k] = true; continue; }
    if (k === 'if') { o[k] = v; continue; } // conditions stay exact, or `then` would fire for kinds it was never meant for
    if (k === 'enum') continue; // dropped: the sibling `type` remains
    o[k] = relax(v);
  }
  if (s.enum && !o.type) o.type = 'string';
  return o;
}
const eventDefs = Object.keys(schemas.events!.$defs).sort();
function buildValidators(): { strict: string; tolerant: string } {
  const mk = () => new Ajv2020({ strict: false, validateFormats: false, allErrors: false, code: { source: true, esm: true, optimize: 1 } });
  const exportsStrict: Record<string, string> = {}; const exportsLoose: Record<string, string> = {};
  const ajv = mk(); const ajvL = mk();
  for (const [name, schema] of Object.entries(schemas)) {
    const id = `https://centcom.dev/contracts/${name}.schema.json`; const s = { ...schema, $id: id };
    ajv.addSchema(s); ajvL.addSchema({ ...relax(s), $id: id });
    if (name !== 'events') { exportsStrict[`write_${name.replace(/-/g, '_')}`] = id; exportsLoose[`read_${name.replace(/-/g, '_')}`] = id; }
    else for (const d of Object.keys(schema.$defs)) { exportsStrict[`write_${d}`] = `${id}#/$defs/${d}`; exportsLoose[`read_${d}`] = `${id}#/$defs/${d}`; }
  }
  /** Ajv's standalone output calls require() for its tiny runtime helpers; turn that into a real ESM import (no eval, no Ajv instance at runtime). */
  const esm = (code: string) => { const imports: string[] = []; const body = code.replace(/(?:const|var|let)\s+(\w+)\s*=\s*require\("(ajv\/dist\/runtime\/[\w/.-]+?)"\)\.default;?/g, (_m, id: string, mod: string) => { imports.push(`import ${id} from ${JSON.stringify(mod + '.js')};`); return ''; }); return imports.join('\n') + '\n' + body; };
  const wrap = (label: string, code: string) => `/* eslint-disable */\n// @ts-nocheck\n${banner}// ${label}\n${esm(code)}\n`;
  return { strict: wrap('Strict validators (write side): reject anything not in the schema.', standaloneCode(ajv, exportsStrict)), tolerant: wrap('Tolerant validators (read side): ignore unknown fields and accept unknown enum values (CT-VER).', standaloneCode(ajvL, exportsLoose)) };
}

/* ---- the small generated tables */
function emitErrors(): string {
  const e = readJson(join(CONTRACTS, 'errors.json')); const list: J[] = [...e.errors].sort((x, y) => x.code.localeCompare(y.code));
  return `${banner}export const ERROR_BASE = ${q(e.base)} as const;\nexport const ERROR_TABLE = ${JSON.stringify(Object.fromEntries(list.map((x) => [x.code, { status: x.status, area: x.area, retryable: x.retryable, title: x.title }])), null, 2)} as const;\nexport type ErrorCode = keyof typeof ERROR_TABLE;\nexport const ERROR_CODES = Object.keys(ERROR_TABLE) as ErrorCode[];\n`;
}
/** The states a client may emit in agent.state: the list in the "Agent-level states" section of 09-state-map.md. (The relay accepts every key of state-map.json.) */
function agentWireStates(allNames: string[]): string[] {
  const md = readFileSync(join(CONTRACTS, '09-state-map.md'), 'utf8'); const i = md.indexOf('## Agent-level states'); if (i < 0) throw new Error('09-state-map.md has no "Agent-level states" section');
  const para = md.slice(i).split('\n').slice(1).find((l) => l.startsWith('`')); if (!para) throw new Error('no state list under "Agent-level states"');
  const names = [...para.matchAll(/`([a-z][a-z0-9-]*)`/g)].map((m) => m[1]!);
  const unknown = names.filter((n) => !allNames.includes(n)); if (unknown.length) throw new Error('09-state-map.md lists states missing from state-map.json: ' + unknown.join(', '));
  return names;
}
function emitStates(): string {
  const st = readJson(join(CONTRACTS, 'state-map.json')); const names = Object.keys(st).sort(); const agent = agentWireStates(names);
  return `${banner}/** Every state the UI knows (all keys of state-map.json). Receivers tolerate names they do not recognise. */\nexport const STATE_NAMES = ${JSON.stringify(names)} as const;\nexport type StateName = (typeof STATE_NAMES)[number];\n/** What a client may emit in agent.state (09-state-map.md, "Agent-level states"). Connectivity, account, limit and social states are client-local and never sent. */\nexport const AGENT_WIRE_STATES = ${JSON.stringify([...agent].sort())} as const;\nexport type AgentWireState = (typeof AGENT_WIRE_STATES)[number];\n`;
}
/** event kind <- schema definition name. Only control.* kinds keep underscores inside their last segment. */
const kindOf = (def: string): string => { const [, ...r] = def.split('_'); return r[0] === 'control' ? `control.${r.slice(1).join('_')}` : r.join('.'); };
function emitKinds(): string {
  const byKind: Record<string, { p: boolean; s: boolean }> = {};
  for (const d of eventDefs) { const k = kindOf(d); (byKind[k] ??= { p: false, s: false })[d[0] === 'p' ? 'p' : 's'] = true; }
  const mode = Object.fromEntries(Object.keys(byKind).sort().map((k) => [k, byKind[k]!.p && byKind[k]!.s ? 'hybrid' : byKind[k]!.s ? 'encrypted' : 'clear']));
  const defOf = Object.fromEntries(eventDefs.map((d) => [d, kindOf(d)]));
  const env = schemas.envelope!; const fields = Object.keys(env.properties).sort(); const types: string[] = env.properties.t.enum;
  return `${banner}/** Every top-level field the envelope schema defines. Writers must not send anything else. */\nexport const FRAME_FIELDS = ${JSON.stringify(fields)} as const;\nexport const FRAME_TYPES = ${JSON.stringify(types)} as const;\nexport type FrameType = (typeof FRAME_TYPES)[number];\nexport type PayloadMode = 'clear' | 'encrypted' | 'hybrid';\nexport const EVENT_MODES = ${JSON.stringify(mode, null, 2)} as const;\nexport type EventKind = keyof typeof EVENT_MODES;\n/** schema definition -> event kind */\nexport const DEF_KIND = ${JSON.stringify(defOf, null, 2)} as const;\n`;
}
async function emitOpenApi(): Promise<{ ts: string; json: string; ops: string }> {
  const text = readFileSync(join(CONTRACTS, 'openapi.yaml'), 'utf8'); const doc = parseYaml(text) as J;
  const types = astToString(await openapiTS(doc as never));
  const ops: Record<string, J> = {};
  for (const [path, item] of Object.entries<J>(doc.paths)) for (const [method, op] of Object.entries<J>(item)) if (op && typeof op === 'object' && op.operationId) ops[op.operationId] = { method: method.toUpperCase(), path, tags: op.tags ?? [], public: Array.isArray(op.security) && op.security.length === 0 };
  const sorted = Object.fromEntries(Object.keys(ops).sort().map((k) => [k, ops[k]]));
  return { ts: `${banner}${types}`, json: JSON.stringify(sortKeys(doc)), ops: `${banner}export const OPERATIONS = ${JSON.stringify(sorted, null, 2)} as const;\nexport type OperationId = keyof typeof OPERATIONS;\nexport interface OpenApiOperation { method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; path: string; tags: readonly string[]; public: boolean }\n` };
}

/* ------------------------------------------------------------------ write */
async function main() {
  const oa = await emitOpenApi();
  const validators = buildValidators();
  const files: Record<string, string> = {
    'types.ts': emitTypes(), 'error-codes.ts': emitErrors(), 'agent-state.ts': emitStates(), 'event-kinds.ts': emitKinds(),
    'contract-version.ts': `${banner}export const CONTRACT_VERSION = ${q(VERSION)} as const;\nexport const CONTRACT_HASH = ${q(createHash('sha256').update(readFileSync(join(CONTRACTS, 'CONTRACTS.lock'))).digest('hex'))} as const;\n`,
    'openapi.ts': oa.ts, 'openapi.json': oa.json + '\n', 'operations.ts': oa.ops, 'validators-strict.ts': validators.strict, 'validators-tolerant.ts': validators.tolerant,
  };
  let stale = 0;
  for (const [name, content] of Object.entries(files)) {
    const p = join(outDir, name); const cur = existsSync(p) ? readFileSync(p, 'utf8') : null;
    if (check) { if (cur !== content) { stale++; console.error('STALE', name); } continue; }
    mkdirSync(outDir, { recursive: true }); writeFileSync(p, content);
  }
  if (check) { if (stale) { console.error(`${stale} generated file(s) differ from contracts/. Run: pnpm --filter @centcom/protocol gen`); process.exit(1); } console.log('generated output is up to date'); return; }
  console.log(`wrote ${Object.keys(files).length} files to ${outDir} (contract ${VERSION})`);
}
main().catch((e) => { console.error(e); process.exit(1); });
