import { Link, createRoute, useSearch } from '@tanstack/react-router';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { rootRoute } from '../app/root.js';
import type { RouteModule } from '../app/types.js';
import { fmt } from '../i18n/index.js';
import { useHttp } from '../lib/http-context.js';
import { Banner, Button, Card, Chip, EmptyState, Input, Skeleton, Table, useToast } from '../ui/index.js';
import { REASON, can } from '../workspace/rbac.js';
import { useRetryAfter } from '../workspace/retry.js';
import { confirmSeats, loadEntitlements, openPortal, pollEntitlements, previewSeats, redeemCoupon, startCheckout, ulid, type SeatPreview } from './data.js';
import { banners, limitRows, limitText, meters, money, planBadge, statusView, type Entitlements, type Money, type Subscription } from './model.js';
import type { WorkspaceRole } from '../workspace/rbac.js';

function useBilling(): { ws?: string; role?: WorkspaceRole; ent?: Entitlements; sub?: Subscription; loaded: boolean; reload(): void; error?: boolean } {
  const http = useHttp(); const [s, setS] = useState<{ ws?: string; role?: WorkspaceRole; ent?: Entitlements; sub?: Subscription; loaded: boolean; error?: boolean }>({ loaded: false }); const [n, setN] = useState(0);
  useEffect(() => { let on = true; void (async () => { try { const me = (await http.call('getMe', {})).data as { active_workspace?: string | { id: string } | null }; const ws = typeof me.active_workspace === 'string' ? me.active_workspace : me.active_workspace?.id; if (!ws) return void (on && setS({ loaded: true })); const w = (await http.call('getWorkspace', { id: ws })).data as { role?: WorkspaceRole }; if (!can(w.role, 'view_billing')) return void (on && setS({ ws, role: w.role, loaded: true })); const [ent, sub] = await Promise.all([loadEntitlements(http, ws), http.call('getSubscription', { id: ws }).then((r) => r.data as Subscription).catch(() => undefined)]); if (on) setS({ ws, role: w.role, ent, sub, loaded: true }); } catch { if (on) setS({ loaded: true, error: true }); } })(); return () => { on = false; }; }, [http, n]);
  return { ...s, reload: () => setN((x) => x + 1) };
}
const Denied = (): React.JSX.Element => <Card title="Billing"><p>{REASON.view_billing}</p></Card>;
export const Num = ({ children }: { children: React.ReactNode }): React.JSX.Element => <span className="cc-num">{children}</span>;
function Overview(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const b = useBilling(); const search = useSearch({ strict: false }) as { checkout?: string }; const retry = useRetryAfter(); const [msg, setMsg] = useState<string>(); const [code, setCode] = useState(''); const polled = useRef(false);
  useEffect(() => { if (search.checkout !== 'success' || !b.ws || !b.ent || polled.current) return; polled.current = true; setMsg('Checking your plan…'); void pollEntitlements(http, b.ws, b.ent.rev, { sleep: (ms) => new Promise((r) => setTimeout(r, ms)), now: () => Date.now() }).then((r) => { setMsg(r.state === 'updated' ? 'Plan updated' : 'Your payment is still being confirmed. This page updates when it is done.'); if (r.state === 'updated') b.reload(); }); }, [search.checkout, b.ws, b.ent, http]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!b.loaded) return <Skeleton lines={4} />; if (b.error) return <Banner tone="danger">Billing could not be loaded.</Banner>; if (!b.ws) return <EmptyState title="No workspace yet">Create a workspace to see billing.</EmptyState>; if (!can(b.role, 'view_billing') || !b.ent) return <Denied />;
  const st = statusView(b.sub, Date.now()); const bs = banners(b.ent, b.sub, Date.now()); const canChange = can(b.role, 'change_plan'); const here = typeof window !== 'undefined' ? `${window.location.origin}/billing` : 'https://app.centcom.dev/billing';
  return <Card title="Billing">{bs.map((x) => <Banner key={x.id} tone={x.tone === 'danger' ? 'danger' : x.tone === 'warning' ? 'warning' : 'info'} title={x.title}>{x.text} {x.action === 'portal' ? <Button disabledReason={canChange ? undefined : REASON.change_plan} onClick={() => void openPortal(http, b.ws!, here).then((r) => (r.ok ? window.location.assign(r.url) : toast('danger', 'The billing portal could not be opened.')))}>Update payment method</Button> : x.action === 'plans' ? <Link to={'/billing/plans' as never}>See plans</Link> : null}</Banner>)}
    {msg ? <p role="status">{msg}</p> : null}
    <p><Chip tone={st.paid ? 'success' : 'neutral'}>{planBadge(b.ent.plan)}</Chip> {st.label}{b.sub ? <> · <Num>{b.sub.seats}</Num> {b.sub.seats === 1 ? 'seat' : 'seats'}</> : null}</p>
    <Table caption="Usage" rows={meters(b.ent)} rowKey={(m) => m.key} columns={[{ key: 'l', header: 'Meter', cell: (m) => m.label }, { key: 'u', header: 'Used', cell: (m) => <Num>{fmt.number(m.used)}</Num> }, { key: 'x', header: 'Limit', cell: (m) => <Num>{m.limitText}</Num> }, { key: 'p', header: 'Level', cell: (m) => (m.pips ? <span aria-label={`${m.used} of ${m.limitText}`}>{m.pips}</span> : m.pct !== undefined ? `${m.pct}%` : '') }]} />
    <Table caption="Plan limits" rows={limitRows(b.ent)} rowKey={(r) => r.key} columns={[{ key: 'l', header: 'Limit', cell: (r) => r.label }, { key: 't', header: 'Value', cell: (r) => <Num>{r.text}</Num> }]} />
    <div><Button onClick={() => void openPortal(http, b.ws!, here).then((r) => (r.ok ? window.location.assign(r.url) : toast('danger', 'The billing portal could not be opened.')))} disabledReason={canChange ? undefined : REASON.change_plan}>Open the billing portal</Button> <Link to={'/billing/plans' as never}>Plans</Link> · <Link to={'/billing/seats' as never}>Seats</Link> · <Link to={'/billing/invoices' as never}>Invoices</Link></div>
    <form onSubmit={(e) => { e.preventDefault(); void redeemCoupon(http, b.ws!, code).then((r) => { if (r.ok) { toast('success', 'Code applied.'); b.reload(); } else if (r.reason === 'rate_limited') retry.arm(r.retryAfterS ?? 1); else toast('danger', 'That code could not be used.'); }); }}><Input label="Coupon code" value={code} onChange={(e) => setCode(e.target.value)} /><Button type="submit" disabledReason={retry.reason ?? (canChange ? (code.trim() ? undefined : 'Enter a code first.') : REASON.change_plan)}>Apply code</Button></form></Card>;
}
interface PlanRow { id: string; name: string; prices: { interval: string; currency: string; amount: number; per_seat?: boolean }[]; limits: Record<string, number | boolean | null> }
function Plans(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const b = useBilling(); const [plans, setPlans] = useState<PlanRow[]>(); const [interval, setInterval_] = useState<'month' | 'year'>('month'); const key = useRef(ulid()); const busy = useRef(false);
  useEffect(() => { void http.listPage('listPlans', {}).then((p) => setPlans(p.data as PlanRow[])).catch(() => setPlans([])); }, [http]);
  if (!b.loaded) return <Skeleton lines={3} />; if (!can(b.role, 'view_billing')) return <Denied />; const canChange = can(b.role, 'change_plan');
  const go = (plan: 'pro' | 'team'): void => { if (busy.current || !b.ws) return; busy.current = true; const origin = window.location.origin; void startCheckout(http, b.ws, { plan, interval, seats: b.sub?.seats }, `${origin}/billing?checkout=success`, `${origin}/billing/plans`, key.current).then((r) => { if (r.ok) window.location.assign(r.url); else { key.current = r.reason === 'conflict' ? ulid() : key.current; toast('danger', r.reason === 'forbidden' ? 'You are not allowed to change the plan.' : r.reason === 'conflict' ? 'That did not go through. Try again.' : 'Checkout could not be started.'); } }).finally(() => { busy.current = false; }); };
  return <Card title="Plans"><label className="cc-label" htmlFor="iv">Billed</label><select id="iv" className="cc-input" value={interval} onChange={(e) => setInterval_(e.target.value as 'month' | 'year')}><option value="month">Monthly</option><option value="year">Yearly</option></select>
    {plans === undefined ? <Skeleton lines={3} /> : plans.filter((p) => p.id !== 'free').map((p) => { const price = p.prices.find((x) => x.interval === interval && x.currency === (b.sub?.currency ?? 'USD')) ?? p.prices.find((x) => x.interval === interval); return <Card key={p.id} title={p.name}><p><Chip>{planBadge(p.id)}</Chip> {price ? <><Num>{money({ amount: price.amount, currency: price.currency })}</Num> {price.per_seat ? 'per seat ' : ''}per {interval}. Tax is added at checkout when it applies.</> : 'Price shown at checkout.'}</p><Button disabledReason={canChange ? undefined : REASON.change_plan} onClick={() => go(p.id as 'pro' | 'team')}>Choose {p.name}</Button></Card>; })}</Card>;
}
function Seats(): React.JSX.Element {
  const http = useHttp(); const { toast } = useToast(); const b = useBilling(); const [n, setN] = useState<number>(); const [prev, setPrev] = useState<SeatPreview>(); const key = useRef(ulid()); const [done, setDone] = useState(false);
  useEffect(() => { if (b.sub && n === undefined) setN(b.sub.seats); }, [b.sub, n]);
  if (!b.loaded) return <Skeleton lines={2} />; if (!can(b.role, 'view_billing')) return <Denied />; const canChange = can(b.role, 'change_plan'); const cur = b.sub?.currency ?? 'USD';
  return <Card title="Seats"><Input label="Seats" type="number" min={1} value={n ?? ''} onChange={(e) => { setN(Math.max(1, Math.floor(Number(e.target.value) || 1))); setPrev(undefined); setDone(false); key.current = ulid(); }} />
    <Button disabledReason={canChange ? (n === b.sub?.seats ? 'That is your current number of seats.' : undefined) : REASON.change_plan} onClick={() => void previewSeats(http, b.ws!, n!).then((r) => (r.ok ? setPrev(r.preview) : toast('danger', r.reason === 'forbidden' ? 'You are not allowed to change seats.' : 'The price could not be worked out.')))}>See the price</Button>
    {prev ? <div role="status"><p>Changing to <Num>{prev.seats}</Num> seats. {prev.proration ? <>Charged now: <Num>{money(prev.proration.amount as Money)}</Num> ({prev.proration.amount.currency}) for the rest of the period{b.sub ? <> that ends on {fmt.date(Date.parse(b.sub.current_period_end), { dateStyle: 'medium', timeZone: 'UTC' })}</> : null}. Tax is added when it applies.</> : <>No charge now ({cur}).</>}</p><Button variant="primary" onClick={() => void confirmSeats(http, b.ws!, n!, key.current).then((r) => { if (r.ok) { setDone(true); setPrev(undefined); b.reload(); } else toast('danger', 'The seats could not be changed.'); })}>Change to {prev.seats} seats</Button> <Button onClick={() => setPrev(undefined)}>Cancel</Button></div> : null}
    {done ? <p role="status">Seats updated.</p> : null}</Card>;
}
interface InvoiceRow { id: string; number?: string; status: string; amount_due: Money; amount_paid: Money; created_at: string; hosted_invoice_url?: string }
function Invoices(): React.JSX.Element {
  const http = useHttp(); const b = useBilling(); const [rows, setRows] = useState<InvoiceRow[]>(); const load = useCallback(() => { if (b.ws) void http.listPage('listInvoices', { id: b.ws }).then((p) => setRows(p.data as InvoiceRow[])).catch(() => setRows([])); }, [http, b.ws]); useEffect(load, [load]);
  if (!b.loaded) return <Skeleton lines={3} />; if (!can(b.role, 'view_billing')) return <Denied />;
  return <Card title="Invoices">{rows === undefined ? <Skeleton lines={3} /> : rows.length ? <Table caption="Invoices" rows={rows} rowKey={(r) => r.id} columns={[{ key: 'n', header: 'Invoice', cell: (r) => r.hosted_invoice_url?.startsWith('https://') ? <a href={r.hosted_invoice_url} rel="noreferrer">{r.number ?? r.id}</a> : (r.number ?? r.id) }, { key: 'd', header: 'Date', cell: (r) => r.created_at.slice(0, 10) }, { key: 's', header: 'Status', cell: (r) => r.status }, { key: 'a', header: 'Amount', cell: (r) => <Num>{money(r.amount_due)}</Num> }, { key: 'p', header: 'Paid', cell: (r) => <Num>{money(r.amount_paid)}</Num> }]} /> : <EmptyState title="No invoices yet">Invoices appear after your first payment.</EmptyState>}</Card>;
}
void useMemo;
const r = (path: string, component: () => React.JSX.Element) => createRoute({ getParentRoute: () => rootRoute, path, component });
export const routeModule: RouteModule = { routes: [r('/billing', Overview), r('/billing/plans', Plans), r('/billing/seats', Seats), r('/billing/invoices', Invoices)], nav: [{ id: 'billing', labelKey: 'nav.billing', to: '/billing', icon: 'billing', requires: { role: ['owner', 'admin', 'billing'] } }] };
export default routeModule; export { limitText };
