import { describe, expect, it } from 'vitest';
import type { FleetManager, FleetNode } from '@centcom/agent';
import { FleetEnginePaused, FleetQueueFull } from '@centcom/agent';
import { runFleet } from '../src/commands/fleet.js';

function io(o: { spawn?: (n: number) => unknown; nodes?: FleetNode[]; orphans?: unknown[] } = {}) {
  const out: string[] = []; const err: string[] = []; const spawned: unknown[] = []; const stopped: string[] = []; let n = 0;
  const fleet = { spawn: async (s: unknown) => { spawned.push(s); const r = o.spawn?.(++n); if (r instanceof Error) throw r; return { id: `agt_0${n}`, branch: `centcom/alex/x-${n}`, state: () => 'queued' }; }, list: () => o.nodes ?? [], paused: () => [], stop: async (id: string) => { stopped.push(id); }, stopAll: async () => { stopped.push('ALL'); }, recoverOrphans: async () => o.orphans ?? [] } as unknown as FleetManager;
  return { io: { fleet, repoRoot: '/r', ownerSlug: 'alex', out: (l: string) => out.push(l), err: (l: string) => err.push(l) }, out, err, spawned, stopped };
}
describe('centcom fleet', () => {
  it('start spawns N agents with numbered labels, for the chosen engine', async () => { const t = io(); expect(await runFleet(['start', '--count', '3', '--engine', 'codex', '--prompt', 'fix it', '--label', 'fix'], t.io)).toBe(0); expect(t.spawned.map((s) => (s as { label: string }).label)).toEqual(['fix-1', 'fix-2', 'fix-3']); expect(t.spawned[0]).toMatchObject({ engine: 'codex', prompt: 'fix it', ownerSlug: 'alex', repoRoot: '/r' }); expect(t.out).toHaveLength(3); });
  it('usage errors', async () => { const t = io(); expect(await runFleet(['start', '--count', '0', '--prompt', 'x'], t.io)).toBe(2); expect(await runFleet(['start', '--engine', 'gemini', '--prompt', 'x'], t.io)).toBe(2); expect(await runFleet(['start'], t.io)).toBe(2); expect(await runFleet(['bogus'], t.io)).toBe(2); expect(await runFleet([], t.io)).toBe(0); expect(t.spawned).toEqual([]); });
  it('a full queue or a paused engine stops the batch with the reason', async () => { const full = io({ spawn: (n) => (n === 2 ? new FleetQueueFull(32) : undefined) }); expect(await runFleet(['start', '--count', '5', '--prompt', 'x'], full.io)).toBe(1); expect(full.spawned).toHaveLength(2); expect(full.err[0]).toContain('32 agents are already waiting'); const paused = io({ spawn: () => new FleetEnginePaused('claude-code', 'limit reached') }); await runFleet(['start', '--count', '3', '--prompt', 'x'], paused.io); expect(paused.spawned).toHaveLength(1); expect(paused.err[0]).toContain('limit reached'); });
  it('list shows children under their parent with branch and attention', async () => { const t = io({ nodes: [{ id: 'agt_01JTEST0000000000000000001', kind: 'agent', state: 'done', label: 'job', branch: 'centcom/a/job-abc123', attention: 'branch ready' }, { id: 'sub_1', parent: 'agt_01JTEST0000000000000000001', kind: 'subagent', state: 'running', label: 'research' }] }); await runFleet(['list'], t.io); expect(t.out[0]).toContain('[branch ready]'); expect(t.out[1]).toContain('└ sub_1'); });
  it('stop by id prefix, stop --all, and an unknown id', async () => { const t = io({ nodes: [{ id: 'agt_01JTEST0000000000000000001', kind: 'agent', state: 'running', label: 'j' }] }); expect(await runFleet(['stop', 'agt_01JTEST'], t.io)).toBe(0); expect(await runFleet(['stop', '--all'], t.io)).toBe(0); expect(t.stopped).toEqual(['agt_01JTEST0000000000000000001', 'ALL']); expect(await runFleet(['stop', 'nope'], t.io)).toBe(2); expect(await runFleet(['stop'], t.io)).toBe(2); });
  it('clean lists leftovers and removes nothing', async () => { const t = io({ orphans: [{ agentId: 'agt_1', branch: 'centcom/a/x-1', path: '/w/1' }, { agentId: 'agt_2', branch: 'centcom/a/x-2', path: '/w/2', missing: true }] }); expect(await runFleet(['clean'], t.io)).toBe(0); expect(t.out.join('\n')).toContain('/w/1'); expect(t.out.join('\n')).toContain('folder is gone'); expect(t.out.at(-1)).toContain('Nothing was removed'); const none = io(); await runFleet(['clean'], none.io); expect(none.out).toEqual(['Nothing left over.']); });
});
