import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import fc from 'fast-check';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { parseSecretPayload } from '@centcom/protocol';
import { CryptoError, DeviceKeyStore, KeyRing, MAX_CT_BYTES, TrustStore, b64, canonicalJson, decryptPayload, encryptPayload, fingerprint, generateInviteSecret, grantKids, initCrypto, inviteSecretFromFragment, joinChunks, memoryKeychain, openGrants, openInviteBundle, pathHmac, pathMacKey, rotationDue, sealGrants, sealInviteBundle, signFrame, sodium, sodiumLoads, splitChunks, unb64, verifyFrame, type FrameHeader } from '../../src/index.js';

const V = JSON.parse(readFileSync(join(import.meta.dirname, '../../../../contracts/fixtures/crypto/vectors.json'), 'utf8'));
const dirs: string[] = []; afterAll(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });
beforeAll(async () => { await Promise.all(Array.from({ length: 10 }, () => initCrypto())); });
const header: FrameHeader = V.xchacha20poly1305.aad_header; const { kid: _k, ...H } = header as FrameHeader & { kid: string }; void _k;
const seedKey = (tag: string) => sodium().crypto_generichash(32, tag, null);
const ringWith = (...kids: string[]) => { const r = new KeyRing(); for (const k of kids) r.addEpoch(k, sodium().crypto_aead_xchacha20poly1305_ietf_keygen()); return r; };

describe('known-answer vectors (acceptance 1)', () => {
  it('XChaCha20-Poly1305 with the fixed key, nonce and AAD gives the exact ciphertext; the AAD is the JCS form', () => { expect(canonicalJson(header)).toBe(V.xchacha20poly1305.aad_jcs); const ct = encryptPayload({ key: unb64(V.keys.session_key_k1), kid: 'k1', header: H as FrameHeader, secret: JSON.parse(V.xchacha20poly1305.plaintext_jcs), nonce: unb64(V.xchacha20poly1305.nonce) }); expect(ct).toEqual({ alg: 'xchacha20poly1305', kid: 'k1', n: V.xchacha20poly1305.nonce, c: V.xchacha20poly1305.ciphertext }); expect(decryptPayload({ keyFor: () => unb64(V.keys.session_key_k1), header: H as FrameHeader, ct })).toEqual({ text: 'add retry logic to the relay client' }); });
  it('Ed25519 over the JCS signed input gives the exact signature, and verifies', () => { const kp = sodium().crypto_sign_seed_keypair(seedKey('centcom/test/device-sign')); expect(b64(kp.publicKey)).toBe(V.keys.device_ed25519_public); const ct = { alg: 'xchacha20poly1305' as const, kid: 'k1', n: V.xchacha20poly1305.nonce, c: V.xchacha20poly1305.ciphertext }; const sig = signFrame(kp.privateKey, { header: H as FrameHeader, ct }); expect(sig).toBe(V.frame_signature.signature); expect(verifyFrame(kp.publicKey, { header: H as FrameHeader, ct }, sig)).toBe(true); });
  it('path MAC key and path_hmac values; the fingerprint; the negative vectors fail', () => {
    expect(b64(pathMacKey(unb64(V.keys.session_key_k1)))).toBe(V.keys.path_mac_key); const r = new KeyRing(); r.addEpoch('k1', unb64(V.keys.session_key_k1)); for (const p of V.path_hmac) expect(pathHmac(r, 'k1', p.path)).toBe(p.hmac);
    expect(fingerprint(V.keys.device_x25519_public, V.keys.device_ed25519_public)).toBe(V.fingerprint); expect(V.fingerprint).toMatch(/^[A-Z2-7]{4}-[A-Z2-7]{4}-[A-Z2-7]{4}$/);
    const key = () => unb64(V.keys.session_key_k1); const base = { alg: 'xchacha20poly1305' as const, kid: 'k1', n: V.xchacha20poly1305.nonce, c: V.xchacha20poly1305.ciphertext };
    expect(() => decryptPayload({ keyFor: key, header: H as FrameHeader, ct: { ...base, c: V.negative[0].ciphertext } })).toThrow(expect.objectContaining({ code: 'aead_failed' })); expect(() => decryptPayload({ keyFor: key, header: H as FrameHeader, ct: { ...base, kid: 'k2' } })).toThrow(expect.objectContaining({ code: 'aead_failed' }));
    expect(verifyFrame(unb64(V.keys.device_ed25519_public), { header: H as FrameHeader, ct: base }, V.negative[2].signature)).toBe(false);
  });
  it('sealed boxes: 48 bytes of overhead and a round trip', () => { const kp = sodium().crypto_box_keypair(); const m = sodium().randombytes_buf(32); const s = sodium().crypto_box_seal(m, kp.publicKey); expect(s.length).toBe(32 + 48); expect(sodium().crypto_box_seal_open(s, kp.publicKey, kp.privateKey)).toEqual(m); });
});
describe('frames (acceptance 2 to 6)', () => {
  const key = sodium.length >= 0 ? undefined : undefined; void key;
  it('every event fixture with a secret payload round-trips and still matches its schema', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); let n = 0; const dir = join(import.meta.dirname, '../../../../contracts/fixtures/events'); for (const f of readdirSync(dir)) { const j = JSON.parse(readFileSync(join(dir, f), 'utf8')); if (!j.secret_payload) continue; const h = { v: 1, t: 'event', id: j.frame.id, sid: j.frame.sid, from_dev: 'dev_01JA3Z8K2M5N7P9Q0R1S2T3V4W', k: j.kind } as FrameHeader; const ct = encryptPayload({ key: k, kid: 'k1', header: h, secret: j.secret_payload }); const back = decryptPayload({ keyFor: () => k, header: h, ct }); expect(back).toEqual(j.secret_payload); expect(parseSecretPayload(j.kind, back).ok, f).toBe(true); n++; } expect(n).toBeGreaterThan(5); });
  it('changing any AAD field breaks decryption (7 mutations); one flipped bit in c, n or sig fails', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); const h = H as FrameHeader; const ct = encryptPayload({ key: k, kid: 'k1', header: h, secret: { text: 'x' } }); for (const [f, v] of [['v', 2], ['t', 'control'], ['id', 'msg_X'], ['sid', 'ses_X'], ['from_dev', 'dev_X'], ['k', 'message.system']] as const) expect(() => decryptPayload({ keyFor: () => k, header: { ...h, [f]: v } as FrameHeader, ct }), f).toThrow(expect.objectContaining({ code: 'aead_failed' })); expect(() => decryptPayload({ keyFor: (id) => (id === 'k9' ? k : undefined), header: h, ct: { ...ct, kid: 'k9' } })).toThrow(expect.objectContaining({ code: 'aead_failed' }));
    const flip = (s: string) => { const b = unb64(s); b[0]! ^= 1; return b64(b); }; expect(() => decryptPayload({ keyFor: () => k, header: h, ct: { ...ct, c: flip(ct.c) } })).toThrow(CryptoError); expect(() => decryptPayload({ keyFor: () => k, header: h, ct: { ...ct, n: flip(ct.n) } })).toThrow(CryptoError);
    const kp = sodium().crypto_sign_keypair(); const sig = signFrame(kp.privateKey, { header: h, ct }); expect(verifyFrame(kp.publicKey, { header: h, ct }, flip(sig))).toBe(false); expect(() => decryptPayload({ keyFor: () => undefined, header: h, ct })).toThrow(expect.objectContaining({ code: 'unknown_kid' }));
  });
  it('hybrid frames sign p; encrypted-only frames do not; another device key fails', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); const h = H as FrameHeader; const ct = encryptPayload({ key: k, kid: 'k1', header: h, secret: { x: 1 } }); const kp = sodium().crypto_sign_keypair(); const other = sodium().crypto_sign_keypair(); const p = { action: 'acquire', path_hmac: 'abc' }; const sig = signFrame(kp.privateKey, { header: h, ct, p }); expect(verifyFrame(kp.publicKey, { header: h, ct, p }, sig)).toBe(true); expect(verifyFrame(kp.publicKey, { header: h, ct, p: { ...p, action: 'release' } }, sig)).toBe(false); expect(verifyFrame(kp.publicKey, { header: h, ct }, sig)).toBe(false); const s2 = signFrame(kp.privateKey, { header: h, ct }); expect(verifyFrame(kp.publicKey, { header: h, ct }, s2)).toBe(true); expect(verifyFrame(other.publicKey, { header: h, ct }, s2)).toBe(false); });
  it('the same plaintext twice gives different nonces and ciphertexts; 100,000 nonces never repeat', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); const a = encryptPayload({ key: k, kid: 'k1', header: H as FrameHeader, secret: { t: 1 } }); const b = encryptPayload({ key: k, kid: 'k1', header: H as FrameHeader, secret: { t: 1 } }); expect(a.n).not.toBe(b.n); expect(a.c).not.toBe(b.c); const seen = new Set<string>(); for (let i = 0; i < 100_000; i++) seen.add(b64(sodium().randombytes_buf(24))); expect(seen.size).toBe(100_000); }, 30_000); // 100,000 libsodium calls: ~6.5 s on a CI runner, over vitest's 5 s default
  it('over 192 KiB is too_large; 500 KiB splits into parts that fit and join back', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); const big = { text: 'x'.repeat(500 * 1024) }; expect(() => encryptPayload({ key: k, kid: 'k1', header: H as FrameHeader, secret: big })).toThrow(expect.objectContaining({ code: 'too_large' })); const parts = splitChunks(big); expect(parts.length).toBeGreaterThan(2); for (const p of parts) expect(encryptPayload({ key: k, kid: 'k1', header: H as FrameHeader, secret: p }).c.length).toBeLessThanOrEqual(MAX_CT_BYTES); const g = (parts[0] as { chunk: { group: string; n: number } }).chunk; expect(parts.every((p) => (p as { chunk: { group: string; n: number } }).chunk.group === g.group && (p as { chunk: { n: number } }).chunk.n === parts.length)).toBe(true); expect(joinChunks([...parts].reverse())).toEqual(big); expect(() => joinChunks(parts.slice(1))).toThrow(CryptoError); });
  it('property: random payloads round-trip and random bit flips are always rejected', () => { const k = sodium().crypto_aead_xchacha20poly1305_ietf_keygen(); fc.assert(fc.property(fc.dictionary(fc.string({ maxLength: 8 }), fc.jsonValue({ maxDepth: 2 })), fc.nat(), (obj, bit) => { const secret = JSON.parse(JSON.stringify(obj)); const ct = encryptPayload({ key: k, kid: 'k1', header: H as FrameHeader, secret }); expect(decryptPayload({ keyFor: () => k, header: H as FrameHeader, ct })).toEqual(secret); const c = unb64(ct.c); c[bit % c.length]! ^= 1 << (bit % 8); expect(() => decryptPayload({ keyFor: () => k, header: H as FrameHeader, ct: { ...ct, c: b64(c) } })).toThrow(CryptoError); }), { numRuns: 200 }); });
});
describe('grants, bundles, rotation (acceptance 7, 8)', () => {
  it('B opens exactly k1 and k2; share-history off seals only the current one; C opens nothing', async () => { const ring = ringWith('k1', 'k2'); const B = new DeviceKeyStore(memoryKeychain(), 'dev_B'); const C = new DeviceKeyStore(memoryKeychain(), 'dev_C'); const bk = await B.getOrCreatePublicKeys(); await C.getOrCreatePublicKeys(); const g = sealGrants(ring, grantKids(ring, true), bk.x25519, 'dev_B'); expect(g.p).toEqual({ to_device: 'dev_B', kids: ['k1', 'k2'] }); const opened = openGrants(B, g.secret); expect(opened.map((o) => o.kid)).toEqual(['k1', 'k2']); expect(opened[1]!.key).toEqual(ring.get('k2')); expect(sealGrants(ring, grantKids(ring, false), bk.x25519).p.kids).toEqual(['k2']); expect(openGrants(C, g.secret)).toEqual([]); });
  it('an invite bundle opens with the secret from the link fragment and not with another', () => { const ring = ringWith('k1', 'k2'); const { secret, fragment } = generateInviteSecret(); expect(fragment).toMatch(/^#k=[A-Za-z0-9_-]{43}$/); const bundle = sealInviteBundle(ring, ['k2'], secret); expect(openInviteBundle(bundle, inviteSecretFromFragment(`https://x/join${fragment}`)).map((k) => k.kid)).toEqual(['k2']); expect(openInviteBundle(bundle, generateInviteSecret().secret)).toEqual([]); });
  it('rotation gives k3, later frames use it, and a ring without k3 cannot read them; schedule thresholds', () => { const t0 = new Date('2026-10-01T00:00:00Z'); const ring = new KeyRing({ now: t0 }); ring.addEpoch('k1', sodium().crypto_aead_xchacha20poly1305_ietf_keygen()); ring.addEpoch('k2', sodium().crypto_aead_xchacha20poly1305_ietf_keygen()); const old = ringWith('k1', 'k2'); const r = ring.rotate('member_removed', t0); expect(r.kid).toBe('k3'); const ct = encryptPayload({ key: ring.current().key, kid: ring.current().kid, header: H as FrameHeader, secret: { a: 1 } }); expect(ct.kid).toBe('k3'); expect(() => decryptPayload({ keyFor: (k) => old.get(k), header: H as FrameHeader, ct })).toThrow(expect.objectContaining({ code: 'unknown_kid' }));
    expect(ring.shouldRotate(new Date(t0.getTime() + 7 * 864e5 - 1), 99_999)).toBeNull(); expect(ring.shouldRotate(new Date(t0.getTime() + 7 * 864e5), 0)).toBe('scheduled'); expect(ring.shouldRotate(t0, 100_000)).toBe('scheduled'); expect(rotationDue(ring, { now: t0, framesSinceRotation: 0, memberRemoved: true })).toBe('member_removed'); expect(() => ring.addEpoch('x9', new Uint8Array(32))).toThrow(CryptoError); });
});
describe('trust, storage, loading (acceptance 9, 10, 11)', () => {
  it('TOFU: new, then match, and changed when a known device brings other keys', async () => { const t = new TrustStore(); const k = { x25519: V.keys.device_x25519_public, ed25519: V.keys.device_ed25519_public }; expect(await t.check('dev_A', k)).toBe('new'); expect(await t.check('dev_A', k)).toBe('match'); expect(await t.check('dev_A', { ...k, ed25519: b64(sodium().crypto_sign_keypair().publicKey) })).toBe('changed'); expect(await t.check('dev_A', k)).toBe('match'); });
  it('no private or session key ever lands in a file; the keychain holds the private halves; a persisted ring is encrypted', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'centcom-crypto-')); dirs.push(dir); const kc = memoryKeychain(); const dev = new DeviceKeyStore(kc); await dev.getOrCreatePublicKeys(); await dev.rebindDeviceId('dev_01JTEST0000000000000000001'); expect([...kc.entries.keys()].sort()).toEqual(['device-keys:dev_01JTEST0000000000000000001']);
    const ring = ringWith('k1', 'k2'); const file = join(dir, 'ring.json'); await ring.persist({ read: async () => readFileSync(file, 'utf8'), write: async (t) => writeFileSync(file, t) }, kc); const trustFile = join(dir, 'trust.json'); await new TrustStore({ read: async () => undefined, write: async (t) => writeFileSync(trustFile, t) }).check('dev_A', await dev.getOrCreatePublicKeys());
    const secrets = [ring.get('k1')!, ring.get('k2')!, dev.signingKey()]; const all = readdirSync(dir).map((f) => readFileSync(join(dir, f), 'utf8')).join('\n'); for (const s of secrets) { expect(all).not.toContain(b64(s)); expect(all).not.toContain(Buffer.from(s).toString('hex')); expect(all).not.toContain(Buffer.from(s).toString('base64')); }
    const back = await KeyRing.restore({ read: async () => readFileSync(file, 'utf8'), write: async () => undefined }, kc); expect(back!.get('k2')).toEqual(ring.get('k2')); expect(await KeyRing.restore({ read: async () => readFileSync(file, 'utf8'), write: async () => undefined }, memoryKeychain())).toBeUndefined();
  });
  it('initCrypto called 10 times at once loads libsodium once', () => { expect(sodiumLoads()).toBe(1); });
});
describe('canonical JSON (RFC 8785)', () => {
  it('orders keys by UTF-16 code units, formats numbers like ECMAScript, escapes minimally', () => { expect(canonicalJson({ b: 1, a: [true, null, 'x'], '€': 1, '\r': 2, '1': 3, '😀': 4 })).toBe('{"\\r":2,"1":3,"a":[true,null,"x"],"b":1,"€":1,"😀":4}'); for (const [n, s] of [[1e21, '1e+21'], [1e-7, '1e-7'], [-0, '0'], [0.1, '0.1'], [123456789012345680000, '123456789012345680000'], [333333333.3333333, '333333333.3333333']] as const) expect(canonicalJson(n)).toBe(s); expect(canonicalJson(' \u0001"')).toBe('" \\u0001\\""'); expect(() => canonicalJson(NaN)).toThrow(); expect(canonicalJson({ a: undefined, b: 1 })).toBe('{"b":1}'); });
});
