import { execFile } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { A, B, lockFiles, rig, tmp } from './helpers.js';

const lockPath = (dir: string) => join(dir, '.centcom/locks', lockFiles(dir)[0]!);
describe('lock files, renewal and expiry (acceptance 3 and 4)', () => {
  it('writes a lock file with only pid, agent id and expiry, under a hashed name', async () => { const r = rig(); await r.client.acquire('src/secret-name.ts', { agentId: A }); expect(lockFiles(r.dir)).toHaveLength(1); expect(lockFiles(r.dir)[0]).toMatch(/^[0-9a-f]{32}\.json$/); const j = JSON.parse(readFileSync(lockPath(r.dir), 'utf8')); expect(Object.keys(j).sort()).toEqual(['agent_id', 'expires_at', 'pid', 'v']); expect(readFileSync(lockPath(r.dir), 'utf8')).not.toContain('secret-name'); });
  it('renews at half the ttl while the agent runs', async () => {
    const r = rig({ running: () => true }); await r.client.acquire('a.ts', { agentId: A, ttlMs: 120_000 }); const first = r.client.check('a.ts')!.expiresAt; await r.clock.advance(59_999); expect(r.client.check('a.ts')!.expiresAt).toBe(first); await r.clock.advance(1); const second = r.client.check('a.ts')!.expiresAt; expect(Date.parse(second) - Date.parse(first)).toBe(60_000);
    for (let i = 0; i < 200 && JSON.parse(readFileSync(lockPath(r.dir), 'utf8')).expires_at !== second; i++) await new Promise((x) => setTimeout(x, 5)); expect(JSON.parse(readFileSync(lockPath(r.dir), 'utf8')).expires_at).toBe(second); await r.clock.advance(600_000); expect(r.client.check('a.ts')).not.toBeNull(); expect(r.events.filter((e) => (e.p as { action: string }).action === 'expire')).toEqual([]);
  });
  it('emits expire exactly once when the agent stops renewing, and cleans up', async () => {
    let running = true; const r = rig({ running: () => running }); await r.client.acquire('a.ts', { agentId: A, ttlMs: 120_000 }); running = false; await r.clock.advance(119_999); expect(r.client.check('a.ts')).not.toBeNull(); await r.clock.advance(1); await r.clock.advance(300_000);
    expect(r.events.filter((e) => (e.p as { action: string }).action === 'expire')).toHaveLength(1); expect(r.client.check('a.ts')).toBeNull(); for (let i = 0; i < 200 && lockFiles(r.dir).length; i++) await new Promise((x) => setTimeout(x, 5)); expect(lockFiles(r.dir)).toEqual([]); expect(r.clock.pending()).toBe(0);
  });
  it('releaseAll on agent exit releases every lock of that agent only', async () => { const r = rig(); for (const f of ['a', 'b', 'c']) await r.client.acquire(f, { agentId: A }); await r.client.acquire('d', { agentId: B }); r.bus.emit('agent:exited', { agent_id: A, outcome: 'crash' }); for (let i = 0; i < 200 && lockFiles(r.dir).length > 1; i++) await new Promise((x) => setTimeout(x, 5)); expect(['a', 'b', 'c'].map((f) => r.client.check(f))).toEqual([null, null, null]); expect(r.client.check('d')).not.toBeNull(); expect(lockFiles(r.dir)).toHaveLength(1); expect(r.events.filter((e) => (e.p as { action: string }).action === 'release')).toHaveLength(3); });
  it('a stale lock file (dead pid) is reclaimed; a live pid is not (block mode)', async () => {
    const dead = rig({ mode: 'block' }); await dead.client.acquire('x', { agentId: A }); const p = lockPath(dead.dir); writeFileSync(p, JSON.stringify({ v: 1, pid: 2_147_483_000, agent_id: B, expires_at: new Date(dead.clock.now() + 60_000).toISOString() })); const fresh = rig({ root: dead.dir, mode: 'block', pid: 4242 }); expect(await fresh.client.acquire('x', { agentId: A })).toEqual({ ok: true }); expect(JSON.parse(readFileSync(p, 'utf8')).pid).toBe(4242);
    const live = rig({ mode: 'block' }); const lp = (() => { mkdirSync(join(live.dir, '.centcom/locks'), { recursive: true }); return join(live.dir, '.centcom/locks'); })(); void lp; const other = rig({ root: live.dir, mode: 'block', pid: process.pid + 0 }); await live.client.acquire('y', { agentId: B }); const file = lockPath(live.dir); const j = JSON.parse(readFileSync(file, 'utf8')); writeFileSync(file, JSON.stringify({ ...j, pid: process.ppid, agent_id: B, expires_at: new Date(live.clock.now() + 60_000).toISOString() }));
    const res = await other.client.acquire('y', { agentId: A }); expect(res).toMatchObject({ ok: false, reason: 'held', heldBy: B });
  });
  it('an expired lock file is reclaimed even if its pid is alive; a damaged one too', async () => { const r = rig({ mode: 'block' }); await r.client.acquire('x', { agentId: A }); const p = lockPath(r.dir); writeFileSync(p, JSON.stringify({ v: 1, pid: process.ppid, agent_id: B, expires_at: new Date(r.clock.now() - 1).toISOString() })); const n = rig({ root: r.dir, mode: 'block', pid: 7 }); expect(await n.client.acquire('x', { agentId: A })).toEqual({ ok: true }); writeFileSync(lockPath(r.dir), '{not json'); const m = rig({ root: r.dir, mode: 'block', pid: 8 }); expect(await m.client.acquire('x', { agentId: B })).toEqual({ ok: true }); });
  it('a lock file that is still being written (empty for a moment) is not taken over', async () => { const r = rig({ mode: 'block' }); await r.client.acquire('x', { agentId: A }); const p = lockPath(r.dir); writeFileSync(p, ''); setTimeout(() => writeFileSync(p, JSON.stringify({ v: 1, pid: process.ppid, agent_id: B, expires_at: new Date(r.clock.now() + 60_000).toISOString() })), 12); const n = rig({ root: r.dir, mode: 'block', pid: 9 }); expect(await n.client.acquire('x', { agentId: A })).toMatchObject({ ok: false, reason: 'held', heldBy: B }); });
  it('in warn mode a live foreign lock is reported as heldBy, and our claim stays in memory only', async () => { const t = tmp(); const a = rig({ root: t.dir, pid: 11 }); await a.client.acquire('f', { agentId: A }); const file = lockPath(t.dir); writeFileSync(file, JSON.stringify({ v: 1, pid: process.ppid, agent_id: A, expires_at: new Date(a.clock.now() + 60_000).toISOString() })); const b = rig({ root: t.dir, pid: 12 }); expect(await b.client.acquire('f', { agentId: B })).toEqual({ ok: true, heldBy: A }); await b.client.release('f', B); expect(existsSync(file)).toBe(true); });
  it('exactly one of six processes wins the same lock file at the same moment', async () => {
    const t = tmp(); mkdirSync(join(t.dir, 'locks')); const file = join(t.dir, 'locks/x.json'); const at = Date.now() + 1500; const tsx = join(import.meta.dirname, '../../../../node_modules/.bin/tsx'); const child = join(import.meta.dirname, 'race-child.ts');
    const outs = await Promise.all(Array.from({ length: 6 }, (_, i) => new Promise<string>((res, rej) => execFile(tsx, [child, file, String(at), `p${i}`], { encoding: 'utf8' }, (e, out) => (e ? rej(e) : res(out.trim()))))));
    expect(outs.filter((o) => o.startsWith('won'))).toHaveLength(1); expect(outs.filter((o) => o.startsWith('lost'))).toHaveLength(5); expect(JSON.parse(readFileSync(file, 'utf8')).agent_id).toBe(outs.find((o) => o.startsWith('won'))!.slice(4));
  }, 60_000);
  it('a lock folder that cannot be written: locks work in memory, with one warning', async () => { const t = tmp(); mkdirSync(join(t.dir, '.centcom'), { recursive: true }); chmodSync(join(t.dir, '.centcom'), 0o500); const r = rig({ root: t.dir }); try { expect(await r.client.acquire('a', { agentId: A })).toEqual({ ok: true }); expect(await r.client.acquire('b', { agentId: A })).toEqual({ ok: true }); expect(r.client.check('a')).not.toBeNull(); if (process.getuid?.() !== 0) expect(r.logs.filter((l) => l.level === 'warn')).toHaveLength(1); } finally { chmodSync(join(t.dir, '.centcom'), 0o700); } });
  it('never touches or locks the user file itself', async () => { const t = tmp(); t.put('src/a.ts', 'data'); const before = readFileSync(join(t.dir, 'src/a.ts'), 'utf8'); const r = rig({ root: t.dir }); await r.client.acquire('src/a.ts', { agentId: A }); await r.client.release('src/a.ts', A); expect(readFileSync(join(t.dir, 'src/a.ts'), 'utf8')).toBe(before); });
  it('1,000 acquire and release cycles with no transport take under 500 ms and send nothing (acceptance 8)', async () => { const r = rig(); let best = Infinity; for (let run = 0; run < 3; run++) { const c0 = process.cpuUsage(); for (let i = 0; i < 1000; i++) { await r.client.acquire(`f${i % 50}.ts`, { agentId: A }); await r.client.release(`f${i % 50}.ts`, A); } const c = process.cpuUsage(c0); best = Math.min(best, (c.user + c.system) / 1000); } expect(best).toBeLessThan(500); /* CPU time, so a busy machine does not fail it */ expect(lockFiles(r.dir)).toEqual([]); }, 30_000);
});
