export interface SlashCommand { name: string; args?: string; desc: string }
export const COMMANDS: SlashCommand[] = [
  { name: 'help', desc: 'Show keys and commands' },
  { name: 'new', desc: 'Start a fresh conversation (the old one stays saved)' },
  { name: 'clear', desc: 'Same as /new: start fresh with an empty context' },
  { name: 'resume', args: '[number|id]', desc: 'Continue a saved conversation from this folder' },
  { name: 'agents', desc: 'Show or hide the fleet panel' },
  { name: 'fleet', args: '[start [n] <task> | stop <n|all> | preview <n> | remove <n> | clean]', desc: 'Run agents in parallel, each in its own worktree and branch' },
  { name: 'mode', args: '[default|edits|plan|bypass]', desc: 'Set how permissions are asked (bypass = dangerously skip permissions)' },
  { name: 'mascot', args: '[large|small|off|auto]', desc: 'Change how big Cento is' },
  { name: 'color', args: '[violet|red|yellow|green|brown]', desc: 'Change Cento\'s colour' },
  { name: 'theme', args: '[dark|light|hc]', desc: 'Switch Graphite / Paper / high contrast' },
  { name: 'motion', args: '[full|reduced]', desc: 'Turn mascot animation on or off' },
  { name: 'cento', args: '[animation]', desc: 'Browse all 319 Cento animations' },
  { name: 'demo', args: '[fix|search|delete|compact|ask|error|limit]', desc: 'Run a scripted demo story' },
  { name: 'model', args: '[name]', desc: 'Pick the model (ctrl+o)' },
  { name: 'effort', args: '[low|medium|high|xhigh|max|default]', desc: 'How hard the agent thinks (pick from a list with no argument)' },
  { name: 'mouse', args: '[on|off]', desc: 'Scroll with the mouse wheel (off lets you select text with the mouse)' },
  { name: 'config', desc: 'Show the settings in effect and where each came from' },
  { name: 'auto', args: '[on|off]', desc: 'Auto skills: apply matching skills and commands to your prompts' },
  { name: 'skills', args: '[filter | enable <id> | disable <id>]', desc: 'List, enable or disable the skills Centcom can auto-apply' },
  { name: 'night', args: '[on|off|start|stop|add <task>|list|remove <n>|clear|allow push|timeout <min>|report]', desc: 'Night cycle: queue many tasks the agent works through while you sleep, without asking you anything' },
  { name: 'interrupt', desc: 'Stop the running agent' },
  { name: 'rewind', args: '[number] [files|conversation|both]', desc: 'Go back to before an earlier prompt (Esc Esc when idle)' },
  { name: 'compact', desc: 'Ask the agent to compact its context' },
  { name: 'usage', desc: 'Tokens, agent time and the cost the tools reported, by conversation, agent and day' },
  { name: 'mcp', args: '[list|status]', desc: 'Show the MCP servers Claude Code and Codex use' },
  { name: 'hooks', args: '[list|validate|templates]', desc: 'Show the Claude Code hooks and check them' },
  { name: 'memory', args: '[show|status]', desc: 'Show the memory files (CLAUDE.md, AGENTS.md); # note adds one' },
  { name: 'permissions', args: '[list | remove <id>]', desc: 'Pick saved permission rules to remove (list prints them)' },
  { name: 'trust', args: 'rules', desc: 'Use this project\'s own permission rules file' },
  { name: 'quit', desc: 'Leave Centcom' },
];
