/** Generates packages/net/src/http/generated/operations.ts from contracts/openapi.yaml. Deterministic: same input, same bytes.
 *    pnpm --filter @centcom/net gen:http                  write
 *    pnpm --filter @centcom/net gen:http --check          exit 1 if the committed output is stale
 *    --spec <openapi.yaml>  read another copy of the contract (tests use this)
 *    --out <file>           write or check another file */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../../..'); const CONTRACTS = join(ROOT, 'contracts');
const args = process.argv.slice(2); const check = args.includes('--check');
const opt = (name: string, fallback: string) => (args.includes(name) ? resolve(args[args.indexOf(name) + 1]!) : fallback);
const specPath = opt('--spec', join(CONTRACTS, 'openapi.yaml'));
const outPath = opt('--out', join(HERE, '../src/http/generated/operations.ts'));

type J = Record<string, any>;
const VERSION: string = JSON.parse(readFileSync(join(CONTRACTS, 'index.json'), 'utf8')).contract_version;
const BANNER = `// GENERATED by packages/net/scripts/gen-http.ts from contracts/openapi.yaml (contract ${VERSION}). Do not edit.\n// Regenerate: pnpm --filter @centcom/net gen:http\n`;
const METHODS = ['get', 'put', 'post', 'patch', 'delete'] as const;
/* CT-PAGE "Request size limits": JSON bodies up to 256 KiB, except POST /v1/usage/events (1 MiB) */
const BODY_LIMIT = 256 * 1024; const BIG_BODIES: Record<string, number> = { 'POST /v1/usage/events': 1024 * 1024 };

function refName(ref: string): string { const m = /^#\/components\/[a-zA-Z]+\/(.+)$/.exec(ref); if (!m) throw new Error('unsupported $ref ' + ref); return m[1]!; }
function deref(doc: J, s: J | undefined): J | undefined {
  let x = s; for (let i = 0; i < 20 && x && typeof x === 'object' && x.$ref; i++) { let cur: any = doc; for (const p of String(x.$ref).replace(/^#\//, '').split('/')) cur = cur?.[p]; if (!cur) throw new Error('unresolvable $ref ' + x.$ref); x = cur; }
  return x;
}

/** The read-side shape of a schema: types, required fields, nesting and refs only. Enums, patterns, formats and lengths are dropped on purpose (CT-VER: readers tolerate unknown values). */
function shape(s: J | boolean | undefined, refs: Set<string>): J {
  if (s === undefined || s === true || (typeof s === 'object' && Object.keys(s).length === 0)) return {};
  if (s === false) throw new Error('schema `false` is not supported');
  if (s.$ref) { const n = refName(s.$ref); refs.add(n); return { ref: n }; }
  const out: J = {};
  if ('const' in s) out.const = s.const;
  const types = Array.isArray(s.type) ? [...s.type] : s.type ? [s.type] : [];
  if (types.length) out.type = types.sort();
  if (s.required?.length) out.required = [...s.required].sort();
  if (s.properties) out.properties = Object.fromEntries(Object.keys(s.properties).sort().map((k) => [k, shape(s.properties[k], refs)]));
  if (s.items) out.items = shape(s.items, refs);
  if (s.additionalProperties && typeof s.additionalProperties === 'object') out.additionalProperties = shape(s.additionalProperties, refs);
  if (s.oneOf || s.anyOf) out.anyOf = (s.oneOf ?? s.anyOf).map((x: J) => shape(x, refs));
  if (s.allOf) out.allOf = s.allOf.map((x: J) => shape(x, refs));
  return out;
}
/** Every property a schema can have, through allOf and refs (used to spot list endpoints). */
function propsOf(doc: J, s: J | undefined): J {
  const x = deref(doc, s); if (!x) return {};
  return Object.assign({}, x.properties ?? {}, ...(x.allOf ?? []).map((p: J) => propsOf(doc, p)));
}
/** JSON with sorted keys, so the output does not depend on YAML key order. */
const sortKeys = (v: any): any => (Array.isArray(v) ? v.map(sortKeys) : v && typeof v === 'object' ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sortKeys(v[k])])) : v);
const json = (v: unknown) => JSON.stringify(sortKeys(v));

export function generate(doc: J): string {
  const ops: Record<string, J> = {}; const types: Record<string, string> = {}; const refs = new Set<string>();
  for (const path of Object.keys(doc.paths ?? {}).sort()) {
    const item = doc.paths[path] as J;
    for (const method of METHODS) {
      const op = item[method] as J | undefined; if (!op?.operationId) continue;
      const id: string = op.operationId; if (ops[id]) throw new Error('duplicate operationId ' + id);
      const params = [...(item.parameters ?? []), ...(op.parameters ?? [])].map((p: J) => deref(doc, p)!);
      const sec: J[] | undefined = op.security ?? doc.security;
      const auth = !sec || sec.length === 0 ? 'none' : sec.some((r) => r && Object.keys(r).length === 0) ? 'optional' : 'required';
      const rb = deref(doc, op.requestBody); const rbSchema = rb?.content?.['application/json']?.schema;
      const success = Object.keys(op.responses ?? {}).filter((s) => /^[23]\d\d$/.test(s)).map(Number).sort((a, b) => a - b);
      const first = success.find((s) => deref(doc, op.responses[String(s)])?.content?.['application/json']);
      const resSchema = first === undefined ? undefined : deref(doc, op.responses[String(first)])!.content['application/json'].schema;
      const rp = propsOf(doc, resSchema);
      const idem = op['x-idempotency'] ?? 'none'; if (!['none', 'accepted', 'required'].includes(idem)) throw new Error(`${id}: unknown x-idempotency ${idem}`);
      ops[id] = {
        method: method.toUpperCase(), path, scopes: [...(op['x-scopes'] ?? [])].sort(), idempotency: idem === 'required' ? 'R' : idem === 'accepted' ? 'A' : 'none', auth,
        pathParams: params.filter((p) => p.in === 'path').map((p) => p.name).sort(), queryParams: params.filter((p) => p.in === 'query').map((p) => p.name).sort(),
        requiredQuery: params.filter((p) => p.in === 'query' && p.required).map((p) => p.name).sort(),
        ifMatch: params.some((p) => p.in === 'header' && p.name.toLowerCase() === 'if-match'),
        body: rbSchema ? (rb!.required ? 'required' : 'optional') : 'none', requestType: rbSchema?.$ref ? refName(rbSchema.$ref) : null,
        success, responseType: resSchema?.$ref ? refName(resSchema.$ref) : null, response: resSchema ? shape(resSchema, refs) : null,
        paginated: rp.data?.type === 'array' && 'next_cursor' in rp && 'has_more' in rp,
        maxBodyBytes: BIG_BODIES[`${method.toUpperCase()} ${path}`] ?? BODY_LIMIT,
      };
      types[id] = `OpenApiPaths[${JSON.stringify(path)}][${JSON.stringify(method)}]`;
    }
  }
  /* close over refs: a schema may point at others */
  const schemas: Record<string, J> = {}; const todo = [...refs];
  while (todo.length) { const n = todo.pop()!; if (schemas[n]) continue; const s = doc.components?.schemas?.[n]; if (!s) throw new Error('missing schema ' + n); const more = new Set<string>(); schemas[n] = shape(s, more); for (const m of more) if (!schemas[m]) todo.push(m); }
  const ids = Object.keys(ops).sort();
  const out: string[] = [BANNER, `import type { OpenApiPaths } from '@centcom/protocol';`, `import type { HttpOperationSpec, Shape } from '../spec.js';`, ''];
  out.push('/** Every REST operation: method, path template, scopes, idempotency (R required, A accepted), auth, parameters, body limit and the read-side response shape. */');
  out.push('export const HTTP_OPERATIONS = {'); for (const id of ids) out.push(`  ${JSON.stringify(id)}: ${json(ops[id])},`); out.push('} as const satisfies Record<string, HttpOperationSpec>;');
  out.push('export type HttpOperationId = keyof typeof HTTP_OPERATIONS;');
  out.push(`/** List endpoints (CT-PAGE): they answer \`{ data, next_cursor, has_more }\`. */\nexport type PaginatedOperationId = ${ids.filter((id) => ops[id]!.paginated).map((id) => JSON.stringify(id)).join(' | ')};`);
  out.push('/** The types generated by @centcom/protocol for each operation (parameters, request body, responses). */');
  out.push('export interface HttpOperationTypes {'); for (const id of ids) out.push(`  ${JSON.stringify(id)}: ${types[id]};`); out.push('}');
  out.push('/** Read-side shapes of the component schemas the responses use. */');
  out.push('export const RESPONSE_SCHEMAS: Record<string, Shape> = {'); for (const n of Object.keys(schemas).sort()) out.push(`  ${JSON.stringify(n)}: ${json(schemas[n])},`); out.push('};');
  return out.join('\n') + '\n';
}

function main() {
  const content = generate(parseYaml(readFileSync(specPath, 'utf8')) as J);
  const cur = existsSync(outPath) ? readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n') : null;
  if (check) {
    if (cur !== content) { console.error(`STALE ${outPath}\nThe HTTP operation table differs from openapi.yaml. Run: pnpm --filter @centcom/net gen:http`); process.exit(1); }
    console.log('http operation table is up to date'); return;
  }
  mkdirSync(dirname(outPath), { recursive: true }); writeFileSync(outPath, content);
  console.log(`wrote ${outPath} (contract ${VERSION})`);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { main(); } catch (e) { console.error(e); process.exit(1); }
}
