// @vitest-environment jsdom
import { RouterProvider, createMemoryHistory } from '@tanstack/react-router';
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import React from 'react';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { buildRouter } from '../../src/app/router.js';
import { HttpProvider } from '../../src/lib/http-context.js';
import { routeModule } from '../../src/settings/routes.js';
import { unread } from '../../src/settings/model.js';
import { ToastProvider } from '../../src/ui/index.js';
import { HttpErr, fakeHttp, type Call } from '../workspace/helpers.js';

afterEach(cleanup); beforeEach(() => { window.scrollTo = () => undefined; unread.set(0); });
const ses = 'ses_01JA3Z8K2M5N7P9Q0R1S2T3V4W'; const n = (i: number, o: Record<string, unknown> = {}) => ({ id: `ntf_${i}`, created_at: 'x', read_at: null, category: 'mention', title_key: 'notif.mention.title', body_key: 'notif.mention.body', params: { session: ses }, priority: 'normal', action: { type: 'open_session', deeplink: `centcom://session/${ses}` }, ...o });
function setup(path: string, extra?: (c: Call) => unknown, pages: Parameters<typeof fakeHttp>[1] = {}) { const http = fakeHttp((c) => extra?.(c) ?? (c.op === 'getMe' ? { user: { display_name: 'Ada', locale: 'en', telemetry: false } } : {}), pages); const { router } = buildRouter({ './settings/routes.tsx': { routeModule } }, createMemoryHistory({ initialEntries: [path] })); render(<ToastProvider ttlMs={0}><HttpProvider http={http}><RouterProvider router={router} /></HttpProvider></ToastProvider>); return http; }
describe('inbox (acceptance 2, 3, 5)', () => {
  it('shows text from keys, links only valid deep links, and sets the unread badge', async () => {
    setup('/notifications', undefined, { listNotifications: () => ({ data: [n(1), n(2, { action: { type: 'open_session', deeplink: 'javascript:alert(1)' }, read_at: 'y' })], has_more: false }) }); await screen.findAllByText(/mentioned/i); expect(screen.getAllByRole('link', { name: 'Open' })).toHaveLength(1); expect(screen.getByRole('link', { name: 'Open' }).getAttribute('href')).toBe(`/s/${ses}`); await waitFor(() => expect(unread.count).toBe(1)); expect(document.body.innerHTML).not.toContain('javascript:');
  });
  it('mark read drops the badge at once and puts it back if the server refuses, within 300 ms', async () => {
    let refuse = true; setup('/notifications', (c) => { if (c.op === 'markNotificationRead') { if (refuse) throw new HttpErr('internal_error', 500); return {}; } return undefined; }, { listNotifications: () => ({ data: [n(1), n(2)], has_more: false }) }); await waitFor(() => expect(unread.count).toBe(2)); const t0 = Date.now(); fireEvent.click(screen.getAllByText('Mark read')[0]!); expect(unread.count).toBe(1); await waitFor(() => expect(unread.count).toBe(2), { timeout: 300 }); expect(Date.now() - t0).toBeLessThan(400); refuse = false; fireEvent.click(screen.getAllByText('Mark read')[0]!); await waitFor(() => expect(unread.count).toBe(1)); expect(screen.getAllByText('Mark read')).toHaveLength(1);
  });
  it('read all sends exactly one request and clears the badge', async () => { const http = setup('/notifications', undefined, { listNotifications: () => ({ data: [n(1), n(2)], has_more: false }) }); await waitFor(() => expect(unread.count).toBe(2)); fireEvent.click(screen.getByText('Mark all read')); expect(unread.count).toBe(0); await waitFor(() => expect(http.calls.filter((c) => c.op === 'markAllNotificationsRead')).toHaveLength(1)); expect(screen.queryAllByText('Mark read')).toHaveLength(0); });
  it('pages by cursor with a Load more button for keyboards', async () => { const http = setup('/notifications', undefined, { listNotifications: (a) => (a.cursor ? { data: [n(3)], next_cursor: null, has_more: false } : { data: [n(1), n(2)], next_cursor: 'c1', has_more: true }) }); const more = await screen.findByText('Load more'); fireEvent.click(more); await waitFor(() => expect(screen.getAllByRole('listitem')).toHaveLength(3)); expect(http.calls.filter((c) => c.op === 'listNotifications')[1]!.args).toMatchObject({ cursor: 'c1', limit: 50 }); expect(screen.queryByText('Load more')).toBeNull(); });
});
describe('account, appearance and devices pages', () => {
  it('account: an invalid name is refused on the page with no request; a good save sends the fields; the telemetry box is off and labelled', async () => { const http = setup('/settings/account'); const name = (await screen.findByLabelText('Display name')) as HTMLInputElement; await waitFor(() => expect(name.value).toBe('Ada')); expect((screen.getByLabelText('Share anonymous usage statistics') as HTMLInputElement).checked).toBe(false); fireEvent.change(name, { target: { value: '' } }); fireEvent.click(screen.getByText('Save')); expect(await screen.findByText(/1 to 40/)).toBeTruthy(); expect(http.calls.some((c) => c.op === 'updateMe')).toBe(false); fireEvent.change(name, { target: { value: 'Ada L' } }); fireEvent.click(screen.getByText('Save')); await waitFor(() => expect(http.calls.some((c) => c.op === 'updateMe')).toBe(true)); expect(http.calls.find((c) => c.op === 'updateMe')!.args.body).toEqual({ display_name: 'Ada L', locale: 'en' }); });
  it('devices: lists, the current one cannot be revoked here, another can', async () => { const http = setup('/settings/devices', undefined, { listDevices: () => ({ data: [{ id: 'dev_1', name: 'Laptop', created_at: '2026-10-01T00:00:00Z', current: true }, { id: 'dev_2', name: 'Phone', created_at: '2026-10-02T00:00:00Z' }], has_more: false }) }); await screen.findByText('Laptop (this one)'); const rows = screen.getAllByRole('row'); expect(within(rows[1]!).getByText('Revoke').getAttribute('aria-disabled')).toBe('true'); fireEvent.click(within(rows[2]!).getByText('Revoke')); await waitFor(() => expect(http.calls.some((c) => c.op === 'revokeDevice' && c.args.id === 'dev_2')).toBe(true)); });
  it('appearance: theme and density controls are labelled and the density choice sticks', async () => { setup('/settings/appearance'); const d = (await screen.findByLabelText('Density')) as HTMLSelectElement; fireEvent.change(d, { target: { value: 'compact' } }); expect(document.documentElement.getAttribute('data-density')).toBe('compact'); expect(within(screen.getByRole('main')).getByLabelText('Theme')).toBeTruthy(); });
  it('the top bar badge has an accessible name with the count', async () => { unread.set(3); const { ShellCtx } = await import('../../src/app/Frame.js'); const { router } = buildRouter({ './settings/routes.tsx': { routeModule } }, createMemoryHistory({ initialEntries: ['/settings/appearance'] })); render(<ShellCtx.Provider value={{ nav: [], connectivity: 'online', inspector: null }}><ToastProvider><HttpProvider http={fakeHttp(() => ({}))}><RouterProvider router={router} /></HttpProvider></ToastProvider></ShellCtx.Provider>); expect(await screen.findByRole('link', { name: 'Notifications, 3 unread' })).toBeTruthy(); });
});
