import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { APP_ORIGIN, CSP, WEB_PREFERENCES, appUrlToFile, isAppUrl, isSafeExternal, mimeFor, permissionAllowed, responseHeaders } from '../src/security.js';

const root = resolve('/srv/web/dist');
describe('what the window may load', () => {
  it('only its own address is an app address', () => { expect(isAppUrl(`${APP_ORIGIN}/`)).toBe(true); expect(isAppUrl(`${APP_ORIGIN}/billing?x=1`)).toBe(true); for (const bad of ['https://centcom.dev/', 'app://evil/', 'app://centcom.evil.example/', 'app://user@centcom/', 'app://centcom:80/', 'file:///etc/passwd', 'javascript:alert(1)', 'data:text/html,x', 'not a url', '']) expect(isAppUrl(bad), bad).toBe(false); });
  it('files come from the app folder only, and screens fall back to index.html', () => { expect(appUrlToFile(`${APP_ORIGIN}/assets/a.js`, root)).toBe(join(root, 'assets/a.js')); expect(appUrlToFile(`${APP_ORIGIN}/`, root)).toBe(join(root, 'index.html')); expect(appUrlToFile(`${APP_ORIGIN}/s/ses_01JA3Z8K2M5N7P9Q0R1S2T3V4W`, root)).toBe(join(root, 'index.html')); expect(appUrlToFile(`${APP_ORIGIN}/workspaces`, root)).toBe(join(root, 'index.html')); expect(appUrlToFile(`${APP_ORIGIN}/mascot/index.json`, root)).toBe(join(root, 'mascot/index.json')); });
  it('nothing leaves the folder: dots, encoded dots, backslashes, null bytes, other hosts', () => { for (const bad of [`${APP_ORIGIN}/../secret.txt`, `${APP_ORIGIN}/assets/../../secret.js`, `${APP_ORIGIN}/%2e%2e/%2e%2e/etc/passwd.txt`, `${APP_ORIGIN}/assets/..%2f..%2fsecret.js`, `${APP_ORIGIN}/assets\\..\\x.js`, `${APP_ORIGIN}/a%00.js`, 'app://other/assets/a.js', 'file:///etc/passwd', `${APP_ORIGIN}/%E0%A4%A.js`]) { const f = appUrlToFile(bad, root); expect(f === undefined || f.startsWith(root + '/') || f === root, bad).toBe(true); expect(f ?? '', bad).not.toContain('..'); } });
  it('only https addresses without credentials go to the system browser', () => { expect(isSafeExternal('https://centcom.dev/docs')).toBe(true); for (const bad of ['http://centcom.dev', 'javascript:alert(1)', 'file:///etc/passwd', 'https://user:pw@centcom.dev', 'centcom://join/x', 'app://centcom/', 'ssh://host', '']) expect(isSafeExternal(bad), bad).toBe(false); });
  it('the only permission is notifications, and only for the app\'s own address', () => { expect(permissionAllowed('notifications', `${APP_ORIGIN}/`)).toBe(true); for (const p of ['media', 'geolocation', 'clipboard-read', 'midi', 'display-capture', 'openExternal', 'fullscreen']) expect(permissionAllowed(p, `${APP_ORIGIN}/`), p).toBe(false); expect(permissionAllowed('notifications', 'https://evil.example/')).toBe(false); });
});
describe('the window itself', () => {
  it('has no Node in the page, a sandbox and isolation', () => { expect(WEB_PREFERENCES).toMatchObject({ contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, allowRunningInsecureContent: false, webviewTag: false, nodeIntegrationInWorker: false, nodeIntegrationInSubFrames: false }); });
  it('serves the same policy as the hosted pages: the CSP is the one in index.html and in _headers', () => { const html = readFileSync(join(process.cwd(), 'apps/web/index.html'), 'utf8'); const headers = readFileSync(join(process.cwd(), 'apps/web/public/_headers'), 'utf8'); expect(html).toContain(`content="${CSP}"`); expect(headers).toContain(`Content-Security-Policy: ${CSP}`); expect(CSP).not.toMatch(/'unsafe-(inline|eval)'/); });
  it('responses carry the policy, the type and no sniffing', () => { const h = responseHeaders('/x/a.js'); expect(h).toMatchObject({ 'content-type': 'text/javascript; charset=utf-8', 'content-security-policy': CSP, 'referrer-policy': 'no-referrer', 'x-content-type-options': 'nosniff' }); expect(mimeFor('a.wasm')).toBe('application/wasm'); expect(mimeFor('a.woff2')).toBe('font/woff2'); expect(mimeFor('a.unknown')).toBe('application/octet-stream'); expect(mimeFor('noext')).toBe('application/octet-stream'); });
});
