// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import React from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { QueueStrip, composerState } from '../../src/session/queue.js';

afterEach(cleanup);
const items = [{ item: 'que_1', submitter: 'mem_me', state: 'queued', position: 0, size: 5, kind: 'message', ts: 't' }, { item: 'que_2', submitter: 'mem_b', state: 'queued', position: 1, size: 5, kind: 'message', ts: 't' }, { item: 'que_3', submitter: 'mem_b', state: 'running', position: null, size: 5, kind: 'message', ts: 't' }];
const strip = (role: 'host' | 'editor' | 'viewer', o: { muted?: boolean; actions?: Record<string, () => void> } = {}) => render(<QueueStrip queue={{ version: 3, items }} role={role} self="mem_me" nameOf={(id) => (id === 'mem_b' ? 'Ben' : 'Me')} slotOf={(id) => (id === 'mem_b' ? 2 : 1)} selfSlot={1} muted={o.muted} textOf={(i) => (i === 'que_2' ? 'Please refactor the very long module right now' : undefined)} actions={o.actions as never} />);
describe('the queue by role (acceptance 4)', () => {
  it('a host sees approve, reject, move, edit and drop on waiting items, and nothing on the running one', () => { const a = { approve: vi.fn(), drop: vi.fn(), move: vi.fn(), reject: vi.fn(), edit: vi.fn() }; strip('host', { actions: a }); expect(screen.getAllByText('Approve')).toHaveLength(2); expect(screen.getAllByText('Drop')).toHaveLength(2); fireEvent.click(screen.getAllByText('Approve')[1]!); expect(a.approve).toHaveBeenCalledWith('que_2'); fireEvent.click(screen.getAllByLabelText('Move down')[0]!); expect(a.move).toHaveBeenCalledWith('que_1', 1); expect(screen.getAllByLabelText('Move up')[0]!.getAttribute('aria-disabled')).toBe('true'); fireEvent.click(screen.getAllByText('Drop')[0]!); expect(a.drop).toHaveBeenCalledWith('que_1'); expect(screen.getAllByText('running').length).toBeGreaterThan(0); expect(screen.getAllByLabelText('Move up')).toHaveLength(2); });
  it('an editor never sees approve; sees Cancel on their own waiting item only', () => { const cancel = vi.fn(); strip('editor', { actions: { cancel } }); expect(screen.queryByText('Approve')).toBeNull(); expect(screen.queryByText('Drop')).toBeNull(); expect(screen.getAllByText('Cancel')).toHaveLength(1); fireEvent.click(screen.getByText('Cancel')); expect(cancel).toHaveBeenCalledWith('que_1'); });
  it('a viewer sees the queue and nothing to press', () => { strip('viewer'); expect(screen.queryAllByRole('button')).toHaveLength(0); expect(screen.getByRole('list', { name: 'Queue, 3 waiting' })).toBeTruthy(); });
  it('a muted editor cannot cancel and is told why', () => { strip('editor', { muted: true }); expect(screen.getByText('Cancel').getAttribute('aria-disabled')).toBe('true'); expect(screen.getByRole('tooltip').textContent).toBe('Muted by host'); });
  it('each chip reads: name, the text cut short, the place; yours says You', () => { strip('host'); const t = document.body.textContent!; expect(t).toContain('You'); expect(t).toContain('Ben'); expect(t).toMatch(/"Please refactor the very l/); expect(t).toContain('#1'); expect(t).toContain('#2'); expect(document.querySelector('.cc-qdot')).toBeTruthy(); });
  it('the empty queue says so', () => { render(<QueueStrip queue={{ version: 0, items: [] }} role="host" self="x" nameOf={() => ''} slotOf={() => 0} />); expect(screen.getByText('Nothing is waiting.')).toBeTruthy(); });
});
describe('the composer by role', () => {
  it('viewer none; muted off with the reason; ended off; reconnecting on with a note; editor and host on', () => { expect(composerState('viewer', false, 'live')).toEqual({ show: false, enabled: false }); expect(composerState('editor', true, 'live')).toEqual({ show: true, enabled: false, reason: 'Muted by host' }); expect(composerState('host', false, 'ended').enabled).toBe(false); expect(composerState('editor', false, 'kicked').reason).toBe('This session is over.'); expect(composerState('editor', false, 'reconnecting')).toMatchObject({ enabled: true }); expect(composerState('editor', false, 'live')).toEqual({ show: true, enabled: true }); expect(composerState('editor', false, 'live', true)).toMatchObject({ enabled: false, reason: 'The host locked the queue.' }); expect(composerState('host', false, 'live', true).enabled).toBe(true); });
});
