import { describe, expect, it } from 'vitest';
import { BACKOFF_BASE_MS, BACKOFF_CAP_MS, backoffDelayMs } from '../../../../packages/net/src/relay/reconnect.js';
import { GuestIngest, initialGuestState, reduceGuestState, type DecodedFrame } from '@centcom/guest';
import { bridge } from '../../shell/src/session/engine.js';
import { PhaseScreen, StatusScreens } from '../../shell/src/session/transcript.js';
import { ME, HOST, fr, roster } from './helpers.js';

describe('reconnect (acceptance 2)', () => {
  it('the delay follows 250 ms x 2^n with a 15 s cap (the net client does the reconnecting)', () => { expect(BACKOFF_BASE_MS).toBe(250); expect(BACKOFF_CAP_MS).toBe(15_000); const max = (n: number) => backoffDelayMs(n, () => 0.999999); expect([0, 1, 2, 3, 5, 6, 10].map(max)).toEqual([249, 499, 999, 1999, 7999, 14999, 14999]); expect(backoffDelayMs(3, () => 0)).toBe(0); });
  it('frames that arrive twice, late or in a different order give the same transcript, with no gap or duplicate', () => { const frames: DecodedFrame[] = [roster('editor'), ...Array.from({ length: 30 }, (_, i) => fr('message.user', HOST, undefined, { text: `m${i}` }))]; const seqs = frames.map((f, i) => ({ ...f, seq: i + 1 })); const run = (list: DecodedFrame[]) => { const ing = new GuestIngest<DecodedFrame>(); let s = initialGuestState({ member: ME, slot: 1, role: 'editor' }); for (const f of list) for (const g of ing.push(f)) s = reduceGuestState(s, g); return s.transcript.map((e) => e.kind === 'user' ? e.text : ''); }; const base = run(seqs); const shuffled = [...seqs].sort((a, b) => ((a.seq! * 7) % 31) - ((b.seq! * 7) % 31)); expect(run([...shuffled, ...seqs.slice(5, 15)])).toEqual(base); expect(base).toHaveLength(30); });
});
describe('the bridge from the client to the page state', () => {
  const handle = () => { const any: ((e: unknown) => void)[] = []; const on: Record<string, ((a?: unknown) => void)[]> = {}; return { h: { id: 's', me: { id: ME, slot: 1, role: 'editor' }, onAny: (f: (e: unknown) => void) => { any.push(f); return () => undefined; }, on: (n: string, f: (a?: unknown) => void) => { (on[n] ??= []).push(f); return () => undefined; }, sendEvent: async () => ({ id: 'x', seq: 1 }) }, emit: (e: unknown) => any.forEach((f) => f(e)), fire: (n: string, a?: unknown) => (on[n] ?? []).forEach((f) => f(a)) }; };
  it('events become transcript entries once, in order; a repeated event changes nothing', () => { const w = handle(); const c = bridge(w.h as never); const ev = (seq: number, kind: string, p?: Record<string, unknown>, secret?: Record<string, unknown>) => ({ kind, seq, id: `msg_${seq}`, from: kind.startsWith('control') ? 'srv' : HOST, ts: 't', ...(p ? { p } : {}), ...(secret ? { secret } : {}), verified: true }); w.emit(ev(2, 'message.user', undefined, { text: 'two' })); expect(c.state().transcript).toHaveLength(0); w.emit(ev(1, 'control.roster', { version: 1, members: [{ id: HOST, name: 'H', slot: 0, role: 'host' }, { id: ME, name: 'Me', slot: 1, role: 'editor' }] })); expect(c.state().transcript.map((e) => (e.kind === 'user' ? e.text : ''))).toEqual(['two']); w.emit(ev(2, 'message.user', undefined, { text: 'two' })); expect(c.state().transcript).toHaveLength(1); expect(c.state().lastSeq).toBe(2); });
  it('the client states and close codes map to the page phases', () => { const w = handle(); const c = bridge(w.h as never); w.fire('state', 'waiting_for_key'); expect(c.state().phase).toBe('waiting_for_key'); w.fire('state', 'reconnecting'); expect(c.state().phase).toBe('reconnecting'); w.fire('ended', { code: 4403 }); expect(c.state().phase).toBe('kicked'); const d = handle(); const e = bridge(d.h as never); d.fire('ended', { code: 4404 }); expect(e.state().phase).toBe('ended'); const f = handle(); const g = bridge(f.h as never); f.fire('removed', { code: 'forbidden' }); expect(g.state().phase).toBe('kicked'); });
  it('each close gets its own words', () => { expect(StatusScreens[4426]).toMatch(/update/i); expect(StatusScreens[4403]).toBe('You were removed from this session.'); expect(StatusScreens[4404]).toBe('This session has ended.'); expect(PhaseScreen).toBeTypeOf('function'); });
});
