// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import React from 'react';
import { afterEach, describe, expect, it } from 'vitest';
import { expectNoA11yViolations } from '../../shell/src/a11y/index.js';
import { PhaseScreen } from '../../shell/src/session/transcript.js';
import { fakeConn, fold, fr, HOST, ME, openPage } from './helpers.js';

afterEach(cleanup);
const approval = (id = 'ap_1') => fr('approval.request', HOST, { approval_id: id, agent_id: 'agt_1', risk: 'high', expires_at: '2026-10-07T13:00:00Z', approver: 'host' }, { summary: 'Run npm test' });
describe('the page in every state (acceptance 4, 6, 7, 8)', () => {
  it('a host sees the approval card; the buttons and the keys a and d send the decision for the focused card', async () => { const f = fakeConn(fold([approval(), fr('message.user', HOST, undefined, { text: 'hello' })], 'host')); openPage(f.conn); const card = await screen.findByLabelText('Approval needed: Run npm test'); fireEvent.click(screen.getByText('Approve (a)')); await waitFor(() => expect(f.sent.at(-1)).toMatchObject({ kind: 'approval.decision', body: { p: { approval_id: 'ap_1', decision: 'allow' } } })); card.focus(); fireEvent.keyDown(card, { key: 'd' }); await waitFor(() => expect(f.sent.at(-1)).toMatchObject({ body: { p: { decision: 'deny' } } })); await expectNoA11yViolations(document.body); });
  it('an editor sees the card without buttons, and the composer; a viewer has no composer', async () => { openPage(fakeConn(fold([approval()], 'editor')).conn); await screen.findByLabelText('Approval needed: Run npm test'); expect(screen.queryByText('Approve (a)')).toBeNull(); expect(screen.getByLabelText('Message')).toBeTruthy(); cleanup(); openPage(fakeConn(fold([], 'viewer')).conn); await screen.findByText('You are watching this session.'); expect(screen.queryByLabelText('Message')).toBeNull(); });
  it('sending a message from the composer goes out as a queue.submit with the text only inside the secret part', async () => { const f = fakeConn(fold([], 'editor')); openPage(f.conn); const box = await screen.findByLabelText('Message'); fireEvent.change(box, { target: { value: 'please add tests' } }); fireEvent.click(screen.getByText('Send')); await waitFor(() => expect(f.sent.at(-1)!.kind).toBe('queue.submit')); const b = f.sent.at(-1)!.body as { secret: { body: string } }; expect(b.secret.body).toBe('please add tests'); expect(JSON.stringify(f.sent.at(-1)!.body)).not.toMatch(/"p":\{[^}]*please/); });
  it('g then q focuses the queue; the deep link ?focus=queue does too; ? is left to the shortcut list', async () => { openPage(fakeConn(fold([], 'editor')).conn, `/s/ses_01JA3Z8K2M5N7P9Q0R1S2T3V4W?focus=queue`); await screen.findByLabelText('Queue'); await waitFor(() => expect(document.activeElement?.id).toBe('queue')); (document.getElementById('composer') as HTMLElement).focus(); (document.activeElement as HTMLElement).blur(); fireEvent.keyDown(document.body, { key: 'g' }); fireEvent.keyDown(document.body, { key: 'q' }); expect(document.activeElement?.id).toBe('queue'); });
  it('the connection chip says relay, and reconnecting shows a banner; the ticket is the engine\'s business and never appears on the page or in the address', async () => { const f = fakeConn(fold([], 'editor')); const { connects } = openPage(f.conn); await screen.findByText('relay'); await act(async () => { f.push({ ...f.conn.state(), phase: 'reconnecting' }); }); expect(screen.getByText('Trying to get back into the session.')).toBeTruthy(); expect(JSON.stringify(connects)).not.toMatch(/ticket/i); expect(window.location.href).not.toMatch(/ticket/i); });
  it('waiting for the key, removed, ended and update-required are full messages', async () => { const base = fold([], 'editor'); for (const [phase, text] of [['waiting_for_key', 'Waiting for the host to let you in'], ['kicked', 'You were removed from this session.'], ['ended', 'This session has ended.']] as const) { cleanup(); openPage(fakeConn({ ...base, phase }).conn); await screen.findByText(text); } cleanup(); render(<PhaseScreen phase="live" code={4426} />); expect(screen.getByText(/needs an update/i)).toBeTruthy(); await expectNoA11yViolations(document.body); });
  it('the first page does not fetch the engine: a non-session route never calls the loader', async () => { const { setSessionLoader } = await import('../../shell/src/session/lazy.js'); let loads = 0; setSessionLoader(async () => { loads++; throw new Error('no'); }); const { RouterProvider, createMemoryHistory } = await import('@tanstack/react-router'); const { buildRouter } = await import('../../shell/src/app/router.js'); const { routeModule } = await import('../../shell/src/home/routes.js'); const { router } = buildRouter({ './home/routes.tsx': { routeModule } }, createMemoryHistory({ initialEntries: ['/'] })); window.scrollTo = () => undefined; render(<RouterProvider router={router} />); await screen.findByText('Nothing here yet'); expect(loads).toBe(0); setSessionLoader(undefined); void ME; });
});
