// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import React from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { TranscriptEntry } from '@centcom/guest';
import { Markdown } from '../../shell/src/session/markdown.js';
import { Entry, TranscriptView } from '../../shell/src/session/transcript.js';
import { MAX_ROWS, estimate, throttled, windowRange } from '../../shell/src/session/window.js';

afterEach(cleanup);
const u = (seq: number, text = `message ${seq}`): TranscriptEntry => ({ kind: 'user', seq, id: `m${seq}`, from: 'x', ts: 't', text });
describe('a 5 000 frame transcript (acceptance 1)', () => {
  it('the window never holds more than 200 rows plus overscan, wherever you scroll, and covers the viewport', () => { const hs = Array.from({ length: 5000 }, () => 60); for (const top of [0, 1000, 150_000, 299_000, 400_000]) { const r = windowRange(hs, top, 600); expect(r.end - r.start, String(top)).toBeLessThanOrEqual(MAX_ROWS); expect(r.top + (r.end - r.start) * 60 + r.bottom).toBe(5000 * 60); if (top < 299_000) expect(r.start * 60).toBeLessThanOrEqual(top); } expect(windowRange([], 0, 600)).toEqual({ start: 0, end: 0, top: 0, bottom: 0 }); });
  it('the page holds at most 250 rows for 5 000 entries and renders them fast', () => { const entries = Array.from({ length: 5000 }, (_, i) => u(i + 1)); const t = performance.now(); const { container } = render(<TranscriptView entries={entries} />); const ms = performance.now() - t; expect(container.querySelectorAll('.cc-row-entry').length).toBeLessThanOrEqual(250); expect(container.querySelectorAll('.cc-row-entry').length).toBeGreaterThan(5); expect(ms).toBeLessThan(2000); const box = screen.getByRole('log'); Object.defineProperty(box, 'scrollTop', { value: 100_000, configurable: true, writable: true }); fireEvent.scroll(box); expect(container.querySelectorAll('.cc-row-entry').length).toBeLessThanOrEqual(250); });
  it('the transcript is a labelled log, and estimates grow with the text', () => { render(<TranscriptView entries={[u(1)]} />); expect(screen.getByRole('log', { name: 'Session transcript' })).toBeTruthy(); expect(estimate('user', 800)).toBeGreaterThan(estimate('user', 10)); expect(estimate('approval', 0)).toBeGreaterThan(estimate('system', 0)); });
});
describe('text is safe (guardrail)', () => {
  it('markup, scripts and images stay text; only http and https links, always with noopener noreferrer', () => { const { container } = render(<Markdown text={'**bold** and `code`\n\n<script>alert(1)</script> <img src=x onerror=alert(1)>\n\n[ok](https://example.com/a) [bad](javascript:alert(1)) [rel](/x) ![pic](https://evil.example/p.png)\n\n- one\n- two\n\n```\n<b>raw</b>\n```'} />); expect(container.querySelector('script, img')).toBeNull(); expect(container.textContent).toContain('<script>alert(1)</script>'); const links = [...container.querySelectorAll('a')]; expect(links.map((a) => a.getAttribute('href'))).toEqual(['https://example.com/a', 'https://evil.example/p.png']); for (const a of links) { expect(a.getAttribute('rel')).toBe('noopener noreferrer'); expect(a.getAttribute('target')).toBe('_blank'); } expect(container.querySelector('strong')!.textContent).toBe('bold'); expect(container.querySelectorAll('li')).toHaveLength(2); expect(container.querySelector('pre code')!.textContent).toBe('<b>raw</b>'); });
  it('remote text in every kind of entry is a text node', () => { const evil = '<img src=x onerror=alert(1)>'; const kinds: TranscriptEntry[] = [u(1, evil), { kind: 'system', seq: 2, id: 'a', from: 'x', ts: 't', level: 'info', text: evil }, { kind: 'tool_request', seq: 3, id: 'b', from: 'x', ts: 't', agentId: 'a', toolId: 't', name: evil, summary: evil, risk: 'low' }, { kind: 'tool_result', seq: 4, id: 'c', from: 'x', ts: 't', agentId: 'a', toolId: 't', status: 'ok', summary: evil }, { kind: 'approval', seq: 5, id: 'd', from: 'x', ts: 't', approvalId: 'ap', agentId: 'a', risk: 'high', summary: evil }]; const { container } = render(<>{kinds.map((e) => <Entry key={e.seq} e={e} isHost />)}</>); expect(container.querySelector('img')).toBeNull(); expect(container.textContent).toContain(evil); });
});
describe('streamed answers (acceptance 3)', () => {
  it('ten updates a second reach the page at most once every 100 ms, and the last one always arrives', () => { let t = 0; const q: { at: number; fn: () => void }[] = []; const c = { now: () => t, setTimeout: (fn: () => void, ms: number) => { q.push({ at: t + ms, fn }); return q.length; }, clearTimeout: () => undefined }; const got: number[] = []; const th = throttled<number>((v) => got.push(v), 100, c); for (let i = 0; i < 100; i++) { t = i * 10; q.filter((x) => x.at <= t).forEach((x) => { q.splice(q.indexOf(x), 1); x.fn(); }); th.push(i); } t = 2000; q.splice(0).forEach((x) => x.fn()); expect(got.length).toBeLessThanOrEqual(11); expect(got.at(-1)).toBe(99); const gaps = got.slice(1).map((_, i) => i); void gaps; });
  it('an unfinished answer shows it is still coming, and a gap says a part is missing', () => { render(<Entry e={{ kind: 'assistant', seq: 1, id: 'a', from: 'x', ts: 't', messageId: 'm', agentId: 'a', text: 'Hello', done: false, gap: true }} isHost={false} />); expect(screen.getByText('Waiting for a missing part…')).toBeTruthy(); expect(screen.getByRole('article', { name: 'Cento' }).textContent).toContain('Hello'); });
  void vi;
});
