import fc from 'fast-check';
import { describe, expect, it } from 'vitest';
import { appUrl, isToken, parseDeepLink } from '../../src/invite/deeplink.js';

const T = 'AbCdEfGhIjKlMnOpQrStUvWxYz0'; const SES = 'ses_01JA3Z8K2M5N7P9Q0R1S2T3V4W';
describe('every row of the CT-DEEPLINK table (acceptance 2, 6)', () => {
  const ok: [string, unknown][] = [[`https://centcom.dev/j/${T}`, { kind: 'join', token: T }], [`centcom://join/${T}`, { kind: 'join', token: T }], [`centcom://join/${T}#k=abcdefghijklmnop`, { kind: 'join', token: T }], [`https://centcom.dev/s/${SES}`, { kind: 'session', id: SES }], [`centcom://session/${SES}`, { kind: 'session', id: SES }], [`centcom://session/${SES}?focus=approval`, { kind: 'session', id: SES, focus: 'approval' }], [`centcom://session/${SES}?focus=queue&x=1`, { kind: 'session', id: SES, focus: 'queue' }],
    ['centcom://auth/callback?code=abcdefgh12345&state=xyzxyzxyz9', { kind: 'auth_callback', code: 'abcdefgh12345', state: 'xyzxyzxyz9' }], ['https://centcom.dev/billing', { kind: 'billing' }], ['centcom://billing', { kind: 'billing' }], [`https://centcom.dev/i/${T}`, { kind: 'invite', token: T }], [`centcom://invite/${T}`, { kind: 'invite', token: T }], [`https://centcom.dev/g/${T}`, { kind: 'share', token: T }], [`centcom://share/${T}`, { kind: 'share', token: T }]];
  for (const [u, want] of ok) it(`accepts ${u.replace(T, '<token>').replace(SES, '<ses>')}`, () => { expect(parseDeepLink(u)).toEqual(want); });
  it('an unknown focus is dropped, not an error; unknown parameters are ignored', () => { expect(parseDeepLink(`centcom://session/${SES}?focus=root`)).toEqual({ kind: 'session', id: SES }); expect(parseDeepLink(`https://centcom.dev/j/${T}?utm=1&x=2`)).toEqual({ kind: 'join', token: T }); });
  it('refuses short tokens, odd characters, other hosts and schemes, extra path parts, credentials and ports', () => {
    for (const bad of ['', 'nonsense', `https://centcom.dev/j/short`, `https://centcom.dev/j/${T}!`, `https://evil.example/j/${T}`, `http://centcom.dev/j/${T}`, `javascript:alert(1)`, `data:text/html,x`, `https://centcom.dev/j/${T}/extra`, `centcom://join/${T}/extra`, `https://user:pw@centcom.dev/j/${T}`, `https://centcom.dev:8443/j/${T}`, `centcom://unknown/${T}`, `centcom://session/ses_short`, `centcom://auth/callback?code=x&state=y`, 'centcom://auth/other?code=abcdefgh1&state=abcdefgh2', `centcom://billing/extra`, `https://centcom.dev.evil.example/j/${T}`, 'x'.repeat(700), `https://centcom.dev/j/${'a'.repeat(65)}`]) expect(parseDeepLink(bad), bad.slice(0, 50)).toBeUndefined();
  });
  it('the app address has no fragment and no key; tokens are checked by the same rule', () => { expect(appUrl({ kind: 'join', token: T })).toBe(`centcom://join/${T}`); expect(appUrl({ kind: 'invite', token: T })).toBe(`centcom://invite/${T}`); expect(isToken(T)).toBe(true); expect(isToken('a'.repeat(26))).toBe(false); expect(isToken(undefined)).toBe(false); expect(isToken('a'.repeat(27))).toBe(true); });
  it('junk never throws and never parses into something with unexpected characters (property)', () => { fc.assert(fc.property(fc.string({ maxLength: 800 }), (s) => { const r = parseDeepLink(s); if (r && 'token' in r) expect(r.token).toMatch(/^[A-Za-z0-9_-]{27,64}$/); }), { numRuns: 400 }); fc.assert(fc.property(fc.webUrl(), (s) => { expect(() => parseDeepLink(s)).not.toThrow(); }), { numRuns: 100 }); });
});
