// @vitest-environment jsdom
import { RouterProvider, createMemoryHistory } from '@tanstack/react-router';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import React from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { buildRouter } from '../../src/app/router.js';
import { setState, reset } from '../../src/auth/store.js';
import { HttpProvider } from '../../src/lib/http-context.js';
import { KeyHolder } from '../../src/invite/fragment.js';
import { acceptInvite, joinViaShare, previewInvite } from '../../src/invite/flow.js';
import { routeModule } from '../../src/invite/routes.js';
import { ToastProvider } from '../../src/ui/index.js';
import { HttpErr, fakeHttp, type Call } from '../workspace/helpers.js';

afterEach(cleanup); beforeEach(() => { window.scrollTo = () => undefined; reset(); });
const T = 'AbCdEfGhIjKlMnOpQrStUvWxYz0'; const K = 'AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA';
const preview = { workspace_name: 'Acme', inviter_name: 'Ada', role: 'editor', expires_at: '2026-10-14T00:00:00Z', has_key_bundle: true };
function page(path: string, o: { extra?: (c: Call) => unknown; signedIn?: boolean } = {}) { if (o.signedIn) setState({ status: 'authenticated' }, true); else setState({ status: 'anonymous' }, true); const http = fakeHttp((c) => o.extra?.(c) ?? (c.op === 'previewInvite' ? preview : {})); const { router } = buildRouter({ './invite/routes.tsx': { routeModule } }, createMemoryHistory({ initialEntries: [path] })); render(<ToastProvider><HttpProvider http={http}><RouterProvider router={router} /></HttpProvider></ToastProvider>); return { http, router }; }
describe('the page (acceptance 1, 3, 4)', () => {
  it('shows who invites you and asks first; the preview request has the token and no fragment; the address is clean', async () => {
    window.history.replaceState(null, '', `/j/${T}#k=${K}`); const { http } = page(`/j/${T}`); expect(await screen.findByText("Join Ada's session?")).toBeTruthy(); expect(http.calls[0]).toMatchObject({ op: 'previewInvite', args: { token: T } }); expect(JSON.stringify(http.calls)).not.toContain(K); expect(window.location.hash).toBe(''); expect(screen.getByText('Open in Centcom')).toBeTruthy(); expect(screen.getByText('Sign in to join')).toBeTruthy(); expect(http.calls.some((c) => c.op === 'acceptInvite')).toBe(false);
  });
  it('a malformed token shows the neutral page with no request at all', async () => { const { http } = page('/j/short'); expect(await screen.findByText("This invite isn't valid anymore.")).toBeTruthy(); expect(screen.getByText('Ask for a new link.')).toBeTruthy(); expect(http.calls).toHaveLength(0); });
  it('expired, revoked and used look the same: one neutral message', async () => { const texts: string[] = []; for (const [code, status] of [['invite_expired', 410], ['invite_revoked', 404], ['invite_used', 409], ['not_found', 404]] as const) { cleanup(); page(`/j/${T}`, { extra: (c) => { if (c.op === 'previewInvite') throw new HttpErr(code, status); return undefined; } }); await screen.findByText("This invite isn't valid anymore."); texts.push(document.body.textContent!); } expect(new Set(texts).size).toBe(1); expect(texts[0]).not.toMatch(/expired|revoked|used/i); });
  it('"Open in Centcom" goes to centcom://join/<token> without the key, and the page stays usable', async () => { const assign = vi.fn(); Object.defineProperty(window, 'location', { value: { ...window.location, assign, hash: `#k=${K}`, pathname: `/j/${T}`, search: '' }, writable: true }); page(`/j/${T}`); fireEvent.click(await screen.findByText('Open in Centcom')); expect(assign).toHaveBeenCalledWith(`centcom://join/${T}`); expect(assign.mock.calls[0]![0]).not.toContain(K); expect(await screen.findByText('If Centcom did not open, you can still join here.')).toBeTruthy(); expect(screen.getByText('Sign in to join')).toBeTruthy(); });
  it('a workspace invite asks about the workspace; a signed-in person must click to join, nothing is accepted on load', async () => { const { http } = page(`/i/${T}`, { signedIn: true }); expect(await screen.findByText('Join the workspace Acme?')).toBeTruthy(); await new Promise((r) => setTimeout(r, 50)); expect(http.calls.some((c) => c.op === 'acceptInvite')).toBe(false); fireEvent.click(screen.getByText('Join in the browser')); await waitFor(() => expect(http.calls.some((c) => c.op === 'acceptInvite')).toBe(true)); });
});
describe('accepting (acceptance 5; failure modes)', () => {
  const holder = () => { const h = new KeyHolder(new Uint8Array([1, 2, 3])); return h; };
  it('accept, fetch the bundle once, open it with the key, then the key is zeroed', async () => { const opened: unknown[] = []; const key = holder(); const http = fakeHttp((c) => (c.op === 'getInviteKeyBundle' ? { bundle: 'sealed' } : { workspace: { id: 'wsp_1' } })); const r = await acceptInvite(http, T, { key, open: async (b, k) => { opened.push([b, [...k]]); }, sleep: async () => undefined, signedIn: true }); expect(r).toMatchObject({ state: 'joined', keyed: true }); expect(http.calls.map((c) => c.op)).toEqual(['acceptInvite', 'getInviteKeyBundle']); expect(opened).toEqual([[{ bundle: 'sealed' }, [1, 2, 3]]]); expect(key.present).toBe(false); });
  it('signed out, malformed or refused accepts do not touch the bundle', async () => { const k = holder(); const http = fakeHttp(() => ({})); expect(await acceptInvite(http, T, { key: k, open: async () => undefined, sleep: async () => undefined, signedIn: false })).toEqual({ state: 'signed_out' }); expect(await acceptInvite(http, 'bad', { key: holder(), open: async () => undefined, sleep: async () => undefined, signedIn: true })).toEqual({ state: 'invalid' }); expect(http.calls).toHaveLength(0); expect(k.present).toBe(false); const gone = fakeHttp((c) => { if (c.op === 'acceptInvite') throw new HttpErr('conflict', 409); return {}; }); expect(await acceptInvite(gone, T, { key: holder(), open: async () => undefined, sleep: async () => undefined, signedIn: true })).toEqual({ state: 'invalid' }); });
  it('no key in the address: the person is let in and waits for the host', async () => { const http = fakeHttp(() => ({ workspace: {} })); expect(await acceptInvite(http, T, { key: new KeyHolder(), open: async () => undefined, sleep: async () => undefined, signedIn: true })).toMatchObject({ state: 'waiting_for_key' }); expect(http.calls.map((c) => c.op)).toEqual(['acceptInvite']); });
  it('a bundle that is gone (the second visit) or a network failure falls back to waiting; failures are tried three times with backoff', async () => { const gone = fakeHttp((c) => { if (c.op === 'getInviteKeyBundle') throw new HttpErr('not_found', 404); return {}; }); expect(await acceptInvite(gone, T, { key: holder(), open: async () => undefined, sleep: async () => undefined, signedIn: true })).toMatchObject({ state: 'waiting_for_key' }); expect(gone.calls.filter((c) => c.op === 'getInviteKeyBundle')).toHaveLength(1);
    const sleeps: number[] = []; const down = fakeHttp((c) => { if (c.op === 'getInviteKeyBundle') throw new HttpErr('internal_error', 500); return {}; }); const k = holder(); expect(await acceptInvite(down, T, { key: k, open: async () => undefined, sleep: async (ms) => void sleeps.push(ms), signedIn: true })).toMatchObject({ state: 'waiting_for_key' }); expect(down.calls.filter((c) => c.op === 'getInviteKeyBundle')).toHaveLength(3); expect(sleeps).toEqual([500, 1000]); expect(k.present).toBe(false); });
  it('the preview is untrusted text: markup in a name is shown as text', async () => { const { http } = page(`/j/${T}`, { extra: (c) => (c.op === 'previewInvite' ? { ...preview, inviter_name: '<img src=x onerror=alert(1)>' } : undefined) }); await screen.findByText(/Join <img src=x onerror=alert\(1\)>'s session\?/); expect(document.querySelector('img')).toBeNull(); void http; });
  it('share links: join as a viewer, rate limits count down, bad tokens never call the server', async () => { const ok = fakeHttp(() => ({ session: 'ses_1' })); expect(await joinViaShare(ok, T)).toMatchObject({ state: 'joined' }); expect(ok.calls[0]).toMatchObject({ op: 'joinViaShareLink', args: { token: T } }); expect(await joinViaShare(fakeHttp(() => { throw new HttpErr('rate_limited', 429, 9); }), T)).toEqual({ state: 'rate_limited', retryAfterS: 9 }); expect(await joinViaShare(fakeHttp(() => { throw new HttpErr('gone', 410); }), T)).toEqual({ state: 'invalid' }); const none = fakeHttp(() => ({})); expect(await joinViaShare(none, 'x')).toEqual({ state: 'invalid' }); expect(none.calls).toHaveLength(0); expect((await previewInvite(none, 'x')).state).toBe('invalid'); });
});
