/** Every state of the state map: the word shown, its glyph, its tone and its visibility tier (DESIGN 11.2: 1 is the most urgent, 8 the calmest). */
export type Tone = 'work' | 'human' | 'good' | 'bad' | 'muted';
export type Tier = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
export const STATE_LABELS: Record<string, { tier: Tier; word: string; glyph: string; tone: Tone }> = {
  'crash': { tier: 1, word: 'crashed', glyph: '✗', tone: 'bad' },
  'error': { tier: 1, word: 'error', glyph: '✗', tone: 'bad' },
  'auth-required': { tier: 1, word: 'sign in', glyph: '!', tone: 'human' },
  'session-expired': { tier: 1, word: 'expired', glyph: '!', tone: 'human' },
  'offline': { tier: 1, word: 'offline', glyph: '○', tone: 'bad' },
  'provider-auth-required': { tier: 1, word: 'sign in', glyph: '!', tone: 'human' },
  'awaiting-approval': { tier: 2, word: 'approval', glyph: '?', tone: 'human' },
  'asking-question': { tier: 2, word: 'question', glyph: '?', tone: 'human' },
  'merge-conflict': { tier: 2, word: 'conflict', glyph: '!', tone: 'human' },
  'rate-limited': { tier: 3, word: 'limited', glyph: '!', tone: 'bad' },
  'quota-reached': { tier: 3, word: 'quota', glyph: '!', tone: 'bad' },
  'context-full': { tier: 3, word: 'full', glyph: '!', tone: 'bad' },
  'cost-alert': { tier: 3, word: 'cost', glyph: '!', tone: 'bad' },
  'provider-cap-reached': { tier: 3, word: 'cap', glyph: '!', tone: 'bad' },
  'provider-policy-blocked': { tier: 3, word: 'blocked', glyph: '!', tone: 'bad' },
  'reconnecting': { tier: 3, word: 'reconnecting', glyph: '↻', tone: 'bad' },
  'warning': { tier: 3, word: 'warning', glyph: '!', tone: 'bad' },
  'tests-fail': { tier: 3, word: 'tests failed', glyph: '✗', tone: 'bad' },
  'ci-fail': { tier: 3, word: 'checks failed', glyph: '✗', tone: 'bad' },
  'denied': { tier: 3, word: 'denied', glyph: '✗', tone: 'bad' },
  'tool-running': { tier: 4, word: 'working', glyph: '●', tone: 'work' },
  'editing-file': { tier: 4, word: 'editing', glyph: '●', tone: 'work' },
  'running-command': { tier: 4, word: 'running', glyph: '●', tone: 'work' },
  'streaming': { tier: 4, word: 'writing', glyph: '●', tone: 'work' },
  'thinking': { tier: 4, word: 'thinking', glyph: '●', tone: 'work' },
  'thinking-hard': { tier: 4, word: 'thinking', glyph: '●', tone: 'work' },
  'planning': { tier: 4, word: 'planning', glyph: '●', tone: 'work' },
  'searching': { tier: 4, word: 'searching', glyph: '●', tone: 'work' },
  'reading-file': { tier: 4, word: 'reading', glyph: '●', tone: 'work' },
  'creating-file': { tier: 4, word: 'creating', glyph: '●', tone: 'work' },
  'deleting-file': { tier: 4, word: 'deleting', glyph: '●', tone: 'work' },
  'prompt-received': { tier: 4, word: 'starting', glyph: '●', tone: 'work' },
  'sub-agent': { tier: 4, word: 'helping', glyph: '●', tone: 'work' },
  'ci-running': { tier: 5, word: 'checks', glyph: '●', tone: 'work' },
  'ci-pass': { tier: 5, word: 'checks passed', glyph: '✓', tone: 'good' },
  'pr-open': { tier: 5, word: 'PR open', glyph: '●', tone: 'good' },
  'pr-merged': { tier: 5, word: 'merged', glyph: '✓', tone: 'good' },
  'deploying': { tier: 5, word: 'deploying', glyph: '●', tone: 'work' },
  'tests-pass': { tier: 5, word: 'tests passed', glyph: '✓', tone: 'good' },
  'background-task': { tier: 6, word: 'background', glyph: '●', tone: 'work' },
  'compacting': { tier: 6, word: 'compacting', glyph: '●', tone: 'work' },
  'saving': { tier: 6, word: 'saving', glyph: '●', tone: 'work' },
  'teammate-joins': { tier: 7, word: 'joined', glyph: '☻', tone: 'muted' },
  'teammate-leaves': { tier: 7, word: 'left', glyph: '☻', tone: 'muted' },
  'teammate-typing': { tier: 7, word: 'typing', glyph: '☻', tone: 'muted' },
  'host-session': { tier: 7, word: 'hosting', glyph: '☻', tone: 'muted' },
  'message-queued': { tier: 7, word: 'queued', glyph: '●', tone: 'muted' },
  'pair-working': { tier: 7, word: 'pairing', glyph: '☻', tone: 'muted' },
  'high-five': { tier: 7, word: 'high five', glyph: '✓', tone: 'good' },
  'welcome-teammate': { tier: 7, word: 'welcome', glyph: '☻', tone: 'muted' },
  'handoff': { tier: 7, word: 'handoff', glyph: '☻', tone: 'muted' },
  'approved': { tier: 7, word: 'approved', glyph: '✓', tone: 'good' },
  'success': { tier: 7, word: 'done', glyph: '✓', tone: 'good' },
  'celebrate': { tier: 7, word: 'done', glyph: '✓', tone: 'good' },
  'update-available': { tier: 7, word: 'update', glyph: 'i', tone: 'muted' },
  'online': { tier: 7, word: 'online', glyph: '●', tone: 'muted' },
  'idle': { tier: 8, word: 'idle', glyph: '○', tone: 'muted' },
  'ready': { tier: 8, word: 'ready', glyph: '○', tone: 'muted' },
  'sleeping': { tier: 8, word: 'sleeping', glyph: '○', tone: 'muted' },
  'away': { tier: 8, word: 'away', glyph: '○', tone: 'muted' },
  'listening': { tier: 8, word: 'listening', glyph: '○', tone: 'muted' },
  'empty': { tier: 8, word: 'empty', glyph: '○', tone: 'muted' },
  'no-results': { tier: 8, word: 'no results', glyph: '○', tone: 'muted' },
  'first-run': { tier: 8, word: 'new', glyph: '○', tone: 'muted' },
};
const seen = new Set<string>();
/** A state this client does not know shows as `working` (and is noted once at debug level by the caller). */
export function stateLabel(state: string, log?: (m: string) => void): { word: string; glyph: string; tone: Tone } {
  const l = STATE_LABELS[state]; if (l) return l; if (!seen.has(state)) { seen.add(state); log?.('fleet.unknown_state'); } return { word: 'working', glyph: '●', tone: 'work' };
}
export const priorityTier = (state: string): Tier => STATE_LABELS[state]?.tier ?? 4;
